### ISSUE TITLE
Octal Adder

### ISSUE THREAD

**Issue by 7twik** [SarthakKeshari/calc_for_everything#10]
### Enter calculator name - 
Octal Adder

### Describe calculator functionality - 
Adds 2 octal number

### Under which category you wish to place it - 
[] Computer Science

**Comment by 7twik** [comment]
Opened this issue, pls assign it to me, will do it at once along with binary adder issue

**Comment by SarthakKeshari** [comment]
@7twik ,
Assigned

You may contribute your code under the folder path -

calc_for_everything\calculators\src\computer_science\OctalAdder
