### ISSUE TITLE
First order differential equation Solver Calculator

### ISSUE THREAD

**Issue by Ayushlion8** [SarthakKeshari/calc_for_everything#100]
### Enter calculator name - 
First_Order_Differential_Equation_Solver

### Describe calculator functionality - 
Input ODE: Allow the user to input a first-order ordinary differential equation. This equation typically takes the form dy/dx = f(x, y), where y is the dependent variable and x is the independent variable.

Initial Condition: Prompt the user to provide an initial condition, such as the value of y at a specific x (e.g., y(x0) = y0). This condition is often required to solve initial value problems.

Solve ODE: Utilize numerical methods or symbolic computation to solve the given differential equation. Depending on the complexity of the equation and the user's requirements, the calculator could use methods like Euler's method, Runge-Kutta methods, or symbolic solvers.

Display Solution: Display the solution to the differential equation, which is typically an expression or a function of x. The solution should include any constants of integration if applicable.

### Under which category you wish to place it - 
- [] Computer Science
- [✔️] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

Hey @SarthakKeshari  I want to build this calculator so please assign it to me.

**Comment by Satvik-Garg** [comment]
@SarthakKeshari  kindly assign it to me

**Comment by SarthakKeshari** [comment]
Hey @Ayushlion8,
Similar issue is already under progress #46.
Closing the issue.

Hope to see you again with some more innovative issues.😃
