### ISSUE TITLE
Type of Angle - acute/right angled/ obtuse/straight/reflex/complete

### ISSUE THREAD

**Issue by Deathanni** [SarthakKeshari/calc_for_everything#107]
### Enter calculator name - 
Angle Type Classifier

### Describe calculator functionality - 
Certainly! Here's a brief description:

Angle Type Classifier

This program determines the type of an angle based on its measurement in degrees. The types of angles it can classify are:

- **Acute Angle:** A narrow angle measuring less than 90 degrees.
- **Right Angle:** An angle that measures exactly 90 degrees, forming an L-shape.
- **Obtuse Angle:** An angle measuring between 90 and 180 degrees, wider than a right angle.
- **Straight Angle:** An angle that measures exactly 180 degrees, forming a straight line.
- **Reflex Angle:** An angle between 180 and 360 degrees, larger than a straight angle.
- **Complete Angle:** An angle that measures exactly 360 degrees, forming a full circle.

Users can input an angle, and the program will determine its type and provide the classification.

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Sam-bhav-20** [comment]
@SarthakKeshari kindly assign this it to me

**Comment by Deathanni** [comment]
Could you please assign this issue to me?

**Comment by rishirohilla** [comment]
@SarthakKeshari please assign this to me

**Comment by Sam-bhav-20** [comment]
@SarthakKeshari kindly assign it

**Comment by SarthakKeshari** [comment]
Hey @Sam-bhav-20,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\angleTypeClassifier

Issue completion deadline - 6th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
