### ISSUE TITLE
Trignometric Values

### ISSUE THREAD

**Issue by mr-kadyan** [SarthakKeshari/calc_for_everything#109]
### Enter calculator name - 
Trigonometric Values

### Describe calculator functionality - 
solving equations involving trigonometric functions like (sin , cos , tan , cosec , sec , cot)
### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_
 Please assign this issue to me

**Comment by Satvik-Garg** [comment]
kindlyt assign it to me

**Comment by SarthakKeshari** [comment]
Hey @mr-kadyan,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\trignometricValueCalc

Issue completion deadline - 6th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
