### ISSUE TITLE
Hexadecimal adder

### ISSUE THREAD

**Issue by 7twik** [SarthakKeshari/calc_for_everything#11]
### Enter calculator name - 
Hexadecimal adder

### Describe calculator functionality - 
Adds 2 Hexadecimal number

### Under which category you wish to place it - 
[] Computer Science

**Comment by 7twik** [comment]
Opened this issue, pls assign this issue to me will complete along with the other 2 issues opened by me

**Comment by SarthakKeshari** [comment]
@7twik,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous 2 issues are closed.

**Comment by 7twik** [comment]
I have fixed this issue, please verify it

**Comment by SarthakKeshari** [comment]
Hey @7twik,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\HexadecimalAdder

Issue completion deadline - 2nd Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
