### ISSUE TITLE
lcm of a numbet 

### ISSUE THREAD

**Issue by dvtushar** [SarthakKeshari/calc_for_everything#110]
### Enter calculator name - 
LCM calculator 

### Describe calculator functionality - 
we will find the lcm of a number 

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics -s
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @dvtushar,
Similar issue is already under progress #99.
Closing the issue.

Hope to see you again with some more innovative issues.😃
