### ISSUE TITLE
Infix to Postfix and Prefix Calculator

### ISSUE THREAD

**Issue by maskboyAvi** [SarthakKeshari/calc_for_everything#119]
### Enter calculator name - 
Infix to Postfix and Prefix Calculator

### Describe calculator functionality - 
Calculator will take Infix expression from the user and Generate the Postfix and Prefix expression for it.

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by maskboyAvi** [comment]
@SarthakKeshari I would like to work on this issue. Please assign it to me ;)

**Comment by SarthakKeshari** [comment]
@maskboyAvi,
How about infix to postfix and prefix?

**Comment by SarthakKeshari** [comment]
Hey @maskboyAvi,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\infixToPostAndPreCalc

Issue completion deadline - 6th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
