### ISSUE TITLE
Chemical Kinetics Calculator

### ISSUE THREAD

**Issue by Ayushlion8** [SarthakKeshari/calc_for_everything#121]
### Enter calculator name - 
Chemical Kinetics Calculator

### Describe calculator functionality - 
Chemical Kinetics Calculator that calculates reaction rates, rate constants, and reaction orders based on experimental data is a complex task. It involves fitting experimental data to different kinetic models, such as zero-order, first-order, second-order reactions, etc. 

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics
- [x] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

Hey @SarthakKeshari, please assign this issue to me :)

**Comment by SarthakKeshari** [comment]
Hey @Ayushlion8,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\chemicalKineticsCalc

Issue completion deadline - 6th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Harshit-Poddar90** [comment]
hello pls assign the task to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Harshit-Poddar90,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\chemicalKineticsCalc

Issue completion deadline - 6th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
