### ISSUE TITLE
NOR Operator

### ISSUE THREAD

**Issue by 7twik** [SarthakKeshari/calc_for_everything#123]
### Enter calculator name - 
NOR operator

### Describe calculator functionality - 
Nor operation of multiple binary numbers

### Under which category you wish to place it - 
- [] Computer Science

**Comment by 7twik** [comment]
I would like to work on this issue

**Comment by SarthakKeshari** [comment]
Hey @7twik,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\norOperator

Issue completion deadline - 6th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by KashniHinduja** [comment]
I would like to work on this issue
