### ISSUE TITLE
Finance Calculator - Expense Tracker

### ISSUE THREAD

**Issue by Bhavyal9** [SarthakKeshari/calc_for_everything#135]
### Enter calculator name - 
Expense Tracker

### Describe calculator functionality - 
I was looking into the list of current calculators and found that expense tracker is incomplete. I would like to work on it.

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [x] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
@Bhavyal9,
Expense tracker is under progress as under #68, due to some breaking changes it has been reverted but will be re-worked by the participant.

Closing this issue.

Hope to see you coming up with more innovative ideas. 🤩

Happy Contributing!!🎉
