### ISSUE TITLE
Percentile Calculator

### ISSUE THREAD

**Issue by Celebi07** [SarthakKeshari/calc_for_everything#143]
### Enter calculator name - 
Percentile Calculator

### Describe calculator functionality - 
The calculator determines the position of a given value within a dataset, expressed as a percentage. It does this by counting how many values in the dataset are lower than the specified value and then converting that count into a percentile. This functionality is valuable for understanding the relative ranking of a value within a dataset.

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by ashishnallana** [comment]
hey @SarthakKeshari I would like to work on it.

**Comment by Celebi07** [comment]
@SarthakKeshari I am already working on it. Can you please assign it to me?

**Comment by SarthakKeshari** [comment]
Hey @Celebi07,
In order to get the issue assigned kindly leave a comment for example - "Kindly assign it to me" or "Hey, I wish to work on this", as per the contribution guidelines.

Happy Contributing!! 🎉

**Comment by ashishnallana** [comment]
@SarthakKeshari  I have removed the "screenshots" folder
