### ISSUE TITLE
Form Builder

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#144]
### Enter calculator name - 
Form Builder

### Describe calculator functionality - 
Design a Form Builder that allows the Form Creater(user) to add Form title on top, heading and subheading in between the form wherever the user finds its necessary. 
Form should be capable of adding as many questions as the User wishes and add answering space in the form of text area(eg- Home address), one liner answers(eg-name, age) and checkbox (eg-married or unmarried).

User should be able to download the form in the form of PDF.

Participant can also get admin-appreciation points for this issue if a watermark stating - "Generated using Calc For Everything" can be added as Form background across the pdf page 

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - (Answer here)

**Comment by aniketsinha5552** [comment]
@SarthakKeshari I would like to work on this issue. Please assign this to me.

We could use htmltoCanvas and jspdf libraries for this.

**Comment by SarthakKeshari** [comment]
Hey @aniketsinha5552,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\formBuilder

Issue completion deadline - 9th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by SarthakKeshari** [comment]
@aniketsinha5552,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by anushka-srivastava22** [comment]
Kindly assign the issue to me
