### ISSUE TITLE
Question Paper Builder

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#145]
### Enter calculator name - 
Question Paper Builder

### Describe calculator functionality - 
Design Question Paper Builder that allows user to add Question Paper Title on the top, heading and sub-heading in between, wherever required by the user.
Question Paper Builder should be able to take MCQ and Text based question-answer as input. And will *require* the user to fill the answers or add key points of the text-based answers on the go while creating the form.

User should be able to download two types of forms here -
1) For the examiner (user in our case) which will contain all the questions and answers to the questions.
2) For students (those to whom the user will distribute the question paper) which will contain the questions and blank space or empty checkboxes to answer the question.

Participants can also get admin-appreciation points for this issue if a watermark stating - "Generated using Calc For Everything" can be added as Question Paper background across the pdf page.

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - (Answer here)

**Comment by maskboyAvi** [comment]
@SarthakKeshari I would like to work on this issue. Please assign me.

**Comment by SarthakKeshari** [comment]
Hey @maskboyAvi,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\questionPaperBuilder

Issue completion deadline - 9th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.
