### ISSUE TITLE
 Profit Margin Calculator

### ISSUE THREAD

**Issue by Heramb4270** [SarthakKeshari/calc_for_everything#146]
### Enter calculator name - 
 Profit Margin Calculator

### Describe calculator functionality - 
Profit Margin Calculator that calculates gross profit margin, operating profit margin, and net profit margin for businesses. By Giving specific financial data as input.

 INPUTS :
 1) Revenue (Total Sales) :  The total revenue generated by the business over a specified period. This is the money earned from selling products or services.

 2) Cost of Goods Sold (COGS) : The direct costs associated with producing or delivering the products or services. This includes materials, labor, and manufacturing expenses.

 3) Operating Expenses :  The indirect costs of running the business, such as rent, utilities, salaries, and marketing expenses.

 4) Interest Expense : The interest paid on loans or debt.

 5) Taxes : The income taxes paid by the business.

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [x] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @Heramb4270, 
How about placing this calculator under Finance category?

**Comment by Heramb4270** [comment]
Yes @SarthakKeshari done putting it under finance

**Comment by SarthakKeshari** [comment]
Hey @Heramb4270,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\profitMarginCalc

Issue completion deadline - 6th Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
