### ISSUE TITLE
Points lie inside/outside/on of quadratic curve

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#147]
### Enter calculator name - 
Points lie inside/outside/on of quadratic curve

### Describe calculator functionality - 
So, this calculator aims to find 3 groups of points that lie inside/outside/on quadratic curve
User will be asked to how many points they want to check (min: 2) and then (x,y) for all the points will be taken as input.
All the points on the curve will be grouped together, the points that inside the curve will be grouped together and the points that lie outside the curve will be grouped together.

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - (Answer here)

**Comment by Sam-bhav-20** [comment]
@SarthakKeshari kindly assign me this

**Comment by SarthakKeshari** [comment]
Hey @Sam-bhav-20,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\pointsInOnOutOfQuadCurveFinder

Issue completion deadline - 9th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by Satvik-Garg** [comment]
@SarthakKeshari kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\pointsInOnOutOfQuadCurveFinder

Issue completion deadline - 11th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
