### ISSUE TITLE
Polynomial Equation Roots Finder

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#148]
### Enter calculator name - 
Polynomial Equation Roots Finder

### Describe calculator functionality - 
Take input as degree(max.: 7) of polynomial and then take inputs for the coefficients of the equation x^n + x^(n-1) + x^(n-2) + ... + constant from the user and display the roots of this polynomial

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - (Answer here)

**Comment by shivangforsure** [comment]
Kindly assign this issue to me @SarthakKeshari.

**Comment by SarthakKeshari** [comment]
Hey @shivangforsure,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\polyEqRootFinder

Issue completion deadline - 9th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by SarthakKeshari** [comment]
@shivangforsure,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by Harshit-Poddar90** [comment]
hello pls assign me

**Comment by SarthakKeshari** [comment]
Hey @Harshit-Poddar90,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\polyEqRootFinder

Issue completion deadline - 9th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @syash7202,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\polyEqRootFinder

Issue completion deadline - 26th Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by WaterCubeGod** [comment]
kindly assign me this @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @WaterCubeGod,
Glad to see your eagerness for contributing 🤩. I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 

#### For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉
