### ISSUE TITLE
Code Editor for Web Dev

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#149]
### Enter calculator name - 
Code Editor for Web Dev

### Describe calculator functionality - 
The editor will take html, css and js code from user and display its result in real time

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - (Answer here)

**Comment by farhanalws4u** [comment]
Hi @SarthakKeshari , this looks interesting to me and I want to work on this. can you please assign me?

**Comment by tiwari00ayush** [comment]
hi @SarthakKeshari can you please assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @farhanalws4u,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\codeEditorWebDev

Issue completion deadline - 9th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by SarthakKeshari** [comment]
Hey @tiwari00ayush,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉

**Comment by farhanalws4u** [comment]
Hi @SarthakKeshari , I want some help. actually i have successfully rendered html css and javacript as an output but i have no idea how can i make that rendered content interactive, i mean if i click on a button, event listener is not working or consoles and alerts are not working. so how can i make that interactive.

**Comment by farhanalws4u** [comment]
I have found the way : )

**Comment by SarthakKeshari** [comment]
@farhanalws4u,
Great to hear, go ahead and implement it. Kudos to you!! ✌️
