### ISSUE TITLE
Advanced on-screen Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#151]
### Enter calculator name - 
Advanced on-screen Calculator

### Describe calculator functionality - 
Design advance on-screen calculator supporting basic operators and some more functionality namely,i.e., trigonometry, log, nth root, value of pi and e

Good UI is expected

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - (Answer here)

**Comment by hiren2599** [comment]
Hi @SarthakKeshari ,I would like to work on this, can you assign me

**Comment by SarthakKeshari** [comment]
Hey @hiren2599,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\advOnScreenCalc

Issue completion deadline - 9th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by hiren2599** [comment]
No Problem, that's fine. I will start working on the task.

**Comment by hiren2599** [comment]
Hey @SarthakKeshari, I will not be able to complete it until this weekend due to personal reasons. you can reassign someone the issue.

**Comment by SarthakKeshari** [comment]
@hiren2599,
Thanks for informing. I appreciate your response action in the community. 

Have a good day!! 😊

**Comment by maskboyAvi** [comment]
@SarthakKeshari I would like to work on this issue. Please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @maskboyAvi,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\advOnScreenCalc

Issue completion deadline - 14th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
