### ISSUE TITLE
Co-prime Finder

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#152]
### Enter calculator name - 
Co-prime Finder

### Describe calculator functionality - 
Given two number, display whether they are co-prime or not

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - (Answer here)

**Comment by shreyashsingh-101** [comment]
Please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @shreyashsingh-101,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\coPrimeFinder

Issue completion deadline - 6th Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
