### ISSUE TITLE
Molecular Weight Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#153]
### Enter calculator name - 
Molecular Weight Calculator

### Describe calculator functionality - 
Given molecular formula, find the molecular weight.
Link for atomic weight reference - https://en.wikipedia.org/wiki/List_of_chemical_elements

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics
- [x] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - (Answer here)

**Comment by hiren2599** [comment]
I would like to work on this, can you plz assign me

**Comment by SarthakKeshari** [comment]
Hey @hiren2599,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\molecularWeightCalc

Issue completion deadline - 6th Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
