### ISSUE TITLE
fraction to  decimal and vice versa

### ISSUE THREAD

**Issue by remonix** [SarthakKeshari/calc_for_everything#156]
### Enter calculator name - 
Your answer

### Describe calculator functionality - 
Your answer

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Satvik-Garg** [comment]
@SarthakKeshari kindly assign it to me

**Comment by SarthakKeshari** [comment]
@remonix and @Satvik-Garg,
Closing this issue, due to incomplete issue template.
