### ISSUE TITLE
Metric Unit Convertor for length(km,m,mm,cm,inch,feet,miles) and weight(kg,g,mg,pound,ounce,tonn)

### ISSUE THREAD

**Issue by srronaksingh** [SarthakKeshari/calc_for_everything#159]
### Enter calculator name - 
Metric Unit Convertor for length(km,m,mm,cm,inch,feet,miles) and weight(kg,g,mg,pound,ounce,tonn)

### Describe calculator functionality - 
Metric Unit Converter simplifies the process of converting between different length and weight units. It's a straightforward tool designed for ease of use, suitable for everyday tasks and projects.

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by srronaksingh** [comment]
kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @srronaksingh,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\metricUnitConverter

Issue completion deadline - 9th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by anushka-srivastava22** [comment]
Kindly assign the issue to me
