### ISSUE TITLE
factorial to number

### ISSUE THREAD

**Issue by Aamnahasan** [SarthakKeshari/calc_for_everything#160]
### Enter calculator name - 
Your answer Aamna Hasan

### Describe calculator functionality - 
Your answer it can calculate the factorial of a number

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by shivam7366** [comment]
Please assign this to me I want to work on it.

**Comment by SarthakKeshari** [comment]
@Aamnahasan,
Similar issue is already under progress #108.
Closing the issue.

Hope to see you again with some more innovative issues.😃

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.
