### ISSUE TITLE
Percentage Calculator

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#163]
### Enter calculator name - 
Percentage Calculator

### Describe calculator functionality - 
We will be calculating the percentage of a number.

### Under which category you wish to place it - 
- [] Computer Science
- [X] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by remonix** [comment]
kindly assign issue to me

**Comment by SarthakKeshari** [comment]
Hey @remonix,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\percentageCalc

Issue completion deadline - 9th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.
