### ISSUE TITLE
Drug Dosage Calculator

### ISSUE THREAD

**Issue by Celebi07** [SarthakKeshari/calc_for_everything#165]
### Enter calculator name - 
Drug Dosage Calculator

### Describe calculator functionality - 
Healthcare providers calculate drug dosages based on patient weight, age, and the specific medication's guidelines. This ensures accurate and safe administration.

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [x] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Celebi07** [comment]
@SarthakKeshari I would like to work on this issue

**Comment by SarthakKeshari** [comment]
Hey @Celebi07,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\drugDosageCalc

Issue completion deadline - 9th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
