### ISSUE TITLE
IPv4 to IPv6 Calculator

### ISSUE THREAD

**Issue by maskboyAvi** [SarthakKeshari/calc_for_everything#170]
### Enter calculator name - 
IPv4 to IPv6 Calculator

### Describe calculator functionality - 
It converts IPv4 addresses given by user to their corresponding IPv6 format. It includes input validation of correct Ipv4 address and display the IPv6 result

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by maskboyAvi** [comment]
@SarthakKeshari Please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @maskboyAvi,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\iPv4ToiPv6Calc

Issue completion deadline - 9th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.
