### ISSUE TITLE
Profit Loss Calculator

### ISSUE THREAD

**Issue by Deathanni** [SarthakKeshari/calc_for_everything#175]
### Enter calculator name - 
Profit Loss Calculator

### Describe calculator functionality - 
A Profit Loss Calculator is a valuable financial tool designed to help individuals and businesses calculate and analyze their Cost Price (CP), Market Price (MP), as well as determine potential gains or losses. By inputting the relevant data, such as the purchase cost (CP) and the selling price (MP) of a product or investment, this calculator provides instant insights into your profit margins. It enables users to assess whether they have gained a profit, suffered a loss, or broken even on a transaction. This tool is essential for making informed pricing decisions, evaluating investment opportunities, and maximizing profitability.

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Deathanni** [comment]
@SarthakKeshari Please assign me this to me

**Comment by SarthakKeshari** [comment]
Hey @Deathanni,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\profitLossCalc

Issue completion deadline - 9th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
