### ISSUE TITLE
APGAR Score Calculator

### ISSUE THREAD

**Issue by Celebi07** [SarthakKeshari/calc_for_everything#176]
### Enter calculator name - 
APGAR Score Calculator

### Describe calculator functionality - 
The APGAR Score Calculator is a tool used to assess the physical condition of a newborn baby immediately after birth. It helps healthcare professionals, typically a nurse or doctor, evaluate the baby's well-being based on five criteria and assign a numerical score to each criterion. These criteria are measured at 1 minute and 5 minutes after birth to provide an initial assessment of the baby's health and a later evaluation to see if there have been any improvements or deteriorations. 

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [x] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Celebi07** [comment]
@SarthakKeshari I would like to work on this issue. :)

**Comment by SarthakKeshari** [comment]
Hey @Celebi07,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\aPGARScoreCalc

Issue completion deadline - 9th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
