### ISSUE TITLE
Bayesian Probability Calculator

### ISSUE THREAD

**Issue by Celebi07** [SarthakKeshari/calc_for_everything#177]
### Enter calculator name - 
Bayesian Probability Calculator

### Describe calculator functionality - 
A Bayesian Probability Calculator is a tool that enables users to perform Bayesian probability calculations, a fundamental concept in Bayesian statistics and machine learning. The calculator typically requires users to input prior probabilities, likelihoods, and evidence to compute posterior probabilities. The calculator then combines these inputs using Bayes' theorem to provide a posterior probability, which represents our updated belief after considering the evidence. This tool is invaluable in fields like machine learning for tasks such as classification, where it's used to make informed decisions based on evolving data and prior knowledge.

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Celebi07** [comment]
@SarthakKeshari I would like to work on this issue

**Comment by SarthakKeshari** [comment]
@Celebi07,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous issues are merged.

**Comment by Celebi07** [comment]
@SarthakKeshari I would like to work on this issue.:)

**Comment by SarthakKeshari** [comment]
Hey @Celebi07,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\bayesianProbabilityCalc

Issue completion deadline - 9th Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
