### ISSUE TITLE
Color Code format Converter 

### ISSUE THREAD

**Issue by atharvsawant2003** [SarthakKeshari/calc_for_everything#178]
### Enter calculator name - 
Color Code format Converter

### Describe calculator functionality - 
Convert color code from the following conversions -
1.rgb to hex 
2.hext to rgb
3.rgb to hsl 
4. hsl to rgb

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by atharvsawant2003** [comment]
@SarthakKeshari  Please assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @atharvsawant2003,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\colorCodeFormatConverter

Issue completion deadline - 9th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
