### ISSUE TITLE
distance between two points in 2d and 3d plane.

### ISSUE THREAD

**Issue by dvtushar** [SarthakKeshari/calc_for_everything#179]
### Enter calculator name - 
distance between two points in 2d and 3d plane.

### Describe calculator functionality - 
it will calculate distance between two points .

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @dvtushar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\distanceFormula

Issue completion deadline - 9th Oct 2:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
