### ISSUE TITLE
Statistics Calculator

### ISSUE THREAD

**Issue by govardhanshah456** [SarthakKeshari/calc_for_everything#18]
### Enter calculator name - 
Statistics Calculator

### Describe calculator functionality - 
Mean, Median, Mode, Variance, Standard Deviation, Sum of data, count of data, range (max-min)

### Under which category you wish to place it - 
[] Mathematics

**Comment by govardhanshah456** [comment]
I would like to work on this

**Comment by SarthakKeshari** [comment]
Hey @govardhanshah456,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\statistics
