### ISSUE TITLE
Water Intake Calculator

### ISSUE THREAD

**Issue by tiwari00ayush** [SarthakKeshari/calc_for_everything#182]
### Enter calculator name - 
Water Intake Calculator

### Describe calculator functionality - 
A water intake calculator is a tool designed to help individuals determine their daily recommended water intake based on various factors that can influence their hydration needs.

1. User Inputs: Weight, age, gender, height, activity level, climate 
2. Basal Metabolic Rate (BMR) Calculation : using Mifflin-St Jeor Equation or Harris-Benedict Equation
3. Adjusting for Activity Level and climate
4. Result : adds up the BMR and any climate-based adjustments ( in L ).

### Under which category you wish to place it - 
- [] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [x] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by tiwari00ayush** [comment]
hey @SarthakKeshari can you please assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @tiwari00ayush,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\waterIntakeCalculator

Issue completion deadline - 9th Oct 2:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
