### ISSUE TITLE
want to add a Loan Emi Calculator

### ISSUE THREAD

**Issue by ADHIRAJ-12** [SarthakKeshari/calc_for_everything#192]
### Enter calculator name - 
Loan Emi Calculator
### Describe calculator functionality - 
Your answer

### Under which category you wish to place it - 

- [] Mathematics
- [] Finance

**Comment by ADHIRAJ-12** [comment]
hey @SarthakKeshari  can you please assign me this issue.I want to add this calculator.

**Comment by SarthakKeshari** [comment]
@ADHIRAJ-12,
This issue has already been covered under issue #61

**Comment by ADHIRAJ-12** [comment]
oh sorry! @SarthakKeshari  
How about a Novelty age calculator ?This calculator calculates your age in various novelty units instead of just years. Users can input their birthdate, and the calculator will determine their age in terms of unique units, such as:

1. Planetary Years: Calculate the user's age on other planets in our solar system. For example, calculate how old they would be on Mars, Venus, or Jupiter.
2. Fruit Years: Represent the user's age in terms of the average lifespan of certain fruits or vegetables.
