### ISSUE TITLE
Triangle Type Finder

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#195]
### Enter calculator name - 
Triangle Type Finder Calculator

### Describe calculator functionality - 
We will find the type of triangle 

### Under which category you wish to place it - 
- [] Computer Science
- [X] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by anushka-srivastava22** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @anushka-srivastava22,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\triangleTypeFinder

Issue completion deadline - 9th Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
