### ISSUE TITLE
Sorting Fractions

### ISSUE THREAD

**Issue by Sk783** [SarthakKeshari/calc_for_everything#196]
### Enter calculator name - 
Fraction Sorting calculator

### Describe calculator functionality - 
It will sort the fractions

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Sk783** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Sk783,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\fractionSortingCalculator

Issue completion deadline - 9th Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
