### ISSUE TITLE
Place and Face Value of Digit

### ISSUE THREAD

**Issue by DanishGBU** [SarthakKeshari/calc_for_everything#199]
### Enter calculator name - 
Place and Face Value of Digit

### Describe calculator functionality - 
 Face value is the actual value of the digit whereas place value is the position of a digit in a number.
### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by DanishGBU** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @DanishGBU,
Assigned.

You may contribute your code under the folder path -
### Hacktoberfest2023\calc_for_everything\calculators\src\mathematical\placeAndFaceValueCalc

Issue completion deadline - 10th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
