### ISSUE TITLE
Add a Copy To Clipboard Feature

### ISSUE THREAD

**Issue by ArnabBCA** [SarthakKeshari/calc_for_everything#20]
*Describe the solution you'd like**
Implement Copy to Clipboard Using ( react-copy-to-clipboard )

A "Copy to Clipboard" feature is essential as it allows users to easily copy large solutions, reducing the chance of errors when manually transcribing information. This feature enhances user experience and efficiency, making it a valuable addition to this application.

**Additional context**
![Copy to Clipboard](https://github.com/SarthakKeshari/calc_for_everything/assets/113178195/0302ed14-b355-424c-82d3-a6391953e3bc)

![Copied](https://github.com/SarthakKeshari/calc_for_everything/assets/113178195/295855d1-4734-41ce-a0fc-835b10b03ba9)

**Comment by ArnabBCA** [comment]
I have already submitted a pull request :)

**Comment by SarthakKeshari** [comment]
@ArnabBCA,
Thanks for the abiding by the guidelines 😊. Hope you'll follow it for further contributions.

Happy contributing!!
