### ISSUE TITLE
Equating Denominator of Fraction

### ISSUE THREAD

**Issue by Rida-Nuha** [SarthakKeshari/calc_for_everything#200]
### Enter calculator name - 
Equating Denominator of FRaction

### Describe calculator functionality - 
when two or more fractions have same denominator it is called common denominator.

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Rida-Nuha** [comment]
kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @Rida-Nuha,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\equatingDenominatorOfFraction

Issue completion deadline - 10th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
