### ISSUE TITLE
Table of a Number 

### ISSUE THREAD

**Issue by girisha-pawan** [SarthakKeshari/calc_for_everything#201]
### Enter calculator name - 
Table of a Number

### Describe calculator functionality - 
It calculates the product of the number and the current iterator and logs it to the console.

### Under which category you wish to place it - 
- [] Computer Science
- [-] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by girisha-pawan** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @girisha-pawan,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\tableOfNumber

Issue completion deadline - 10th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
