### ISSUE TITLE
Factors of a number

### ISSUE THREAD

**Issue by Upadhyay-Harshit** [SarthakKeshari/calc_for_everything#202]
### Enter calculator name - 
Factors of a number

### Describe calculator functionality - 
We will find the factors of a number

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\factorsOfNumber

Issue completion deadline - 10th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
