### ISSUE TITLE
 Novelty age calculator 

### ISSUE THREAD

**Issue by ADHIRAJ-12** [SarthakKeshari/calc_for_everything#203]
### Enter calculator name - 
 Novelty age calculator 

### Describe calculator functionality - 
This calculator calculates your age in various novelty units instead of just years. Users can input their birthdate, and the calculator will determine their age in terms of unique units, such as:

Planetary Years: Calculate the user's age on other planets in our solar system. For example, calculate how old they would be on Mars, Venus, or Jupiter.
Fruit Years: Represent the user's age in terms of the average lifespan of certain fruits or vegetables.

### Under which category you wish to place it - 

- [] Mathematics
- [] Scientific
- [x] Let project owner decide

**Comment by imsoumik03** [comment]
@SarthakKeshari kindly assign me this

**Comment by SarthakKeshari** [comment]
Hey @imsoumik03,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\noveltyAgeCalculator

Issue completion deadline - 15th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by ADHIRAJ-12** [comment]
Hey @SarthakKeshari  this issue was created by me as i wanted to add a calculator. Can you please assign it to me..i was waiting for you to assign this to me since very long.

**Comment by uttkarsh1m** [comment]
hey @SarthakKeshari kindly assign it to me

**Comment by SarthakKeshari** [comment]
Hey @uttkarsh1m,
Glad to see your eagerness for contributing 🤩. I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 

#### For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉

**Comment by uttkarsh1m** [comment]
hello @SarthakKeshari i guess the deadline has ended now and the participant did not raised any pr yet . So kindly assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @uttkarsh1m,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\noveltyAgeCalculator

Issue completion deadline - 18th Oct 9:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
