### ISSUE TITLE
Upgrading Searching Visualizer

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#205]
### Enter calculator name - 
Upgrading Searching Visualizer

### Describe calculator functionality - 
Take Input from user whether user wants to search via linear, binary or interpolation search

### Under which category you wish to place it - 
- [X] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by anushka-srivastava22** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @anushka-srivastava22,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\searching_visualizer

#### Be careful, do not break the already existing code. Old code was made as a part of - Searching Visualizer

Issue completion deadline - 10th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
