### ISSUE TITLE
Area of 2D shapes - circle, square, triangle, rectangle, oval

### ISSUE THREAD

**Issue by Sk783** [SarthakKeshari/calc_for_everything#207]
### Enter calculator name - 
2D Area calculator

### Describe calculator functionality - 
it will calculate the area of 2D shapes

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Sk783** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by PrachiDev11** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Sk783,
Assigned.

You may contribute your code under the folder path -
### Hacktoberfest2023\calc_for_everything\calculators\src\mathematical\areaOf2DShapes

Issue completion deadline - 12th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
