### ISSUE TITLE
mixed fraction to improper fraction vice versa

### ISSUE THREAD

**Issue by munfaridzahera** [SarthakKeshari/calc_for_everything#209]
### Enter calculator name -
mixed fraction to improper fraction vice versa

### Describe calculator functionality
converting mixed fraction to improper fraction and vice versa

### Under which category you wish to place it - 
- [ ] Computer Science
- [x ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by munfaridzahera** [comment]
kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @munfaridzahera,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\mixedToImproperAndImproperToMixedFraction

Issue completion deadline - 12th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
