### ISSUE TITLE
add distance converter

### ISSUE THREAD

**Issue by Vimal-Dubey** [SarthakKeshari/calc_for_everything#212]
### Enter calculator name - 
Distance unit converter

### Describe calculator functionality - 
The length converter calculator typically provides a user-friendly interface where you can input a value in one unit and select the desired unit of measurement to convert to. Upon entering the values, the calculator performs the conversion and displays the converted result.

### Under which category you wish to place it - 
- [x ] Computer Science
- [x ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [x ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Vimal-Dubey** [comment]
wants this issue assigned to me

**Comment by SarthakKeshari** [comment]
This is issue has already been covered.
