### ISSUE TITLE
add speed converter

### ISSUE THREAD

**Issue by Vimal-Dubey** [SarthakKeshari/calc_for_everything#213]
### Enter calculator name - 
Speed unit converter

### Describe calculator functionality - 
A speed converter calculator is a tool that helps convert speeds between different units of measurement. It can be used to convert measurements such as miles per hour, kilometers per hour, or meters per second.

### Under which category you wish to place it - 
- [x ] Computer Science
- [x ] Mathematics
- [x ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Vimal-Dubey** [comment]
wants this issue assigned to me

**Comment by Aryan-Dahiya-23** [comment]
Kindly Assign this issue to me.

**Comment by SarthakKeshari** [comment]
@Vimal-Dubey,
May add Pressure Converter with the same issue. Sound good?

**Comment by MrDBC** [comment]
> @Vimal-Dubey, May add Pressure Converter with the same issue. Sound good?

yes , sounds good
what are the different units i need to use for pressure?

**Comment by SarthakKeshari** [comment]
Hey @MrDBC,
If no response is received from @Vimal-Dubey within 24 hours, then I will assign it to you.

**Comment by Rishika631** [comment]
Can you please assign this issue to me

**Comment by SarthakKeshari** [comment]
@Rishika631,
May add Pressure Converter with the same issue. Sound good?

**Comment by Rishika631** [comment]
Sure.Can you tell me what units to add for pressure converter?

**Comment by SarthakKeshari** [comment]
@Rishika631,
You may add these units - 
![image](https://github.com/SarthakKeshari/calc_for_everything/assets/55992140/48716b71-4320-4e0b-8fd3-976dbe75212c)

**Comment by Rishika631** [comment]
sure I'll add both of them. I should make two different files for it right? one named pressure convertor and one named speed convertor?

**Comment by Rishika631** [comment]
@SarthakKeshari can you please add file folders for it in physics category

**Comment by SarthakKeshari** [comment]
> sure I'll add both of them. I should make two different files for it right? one named pressure convertor and one named speed convertor?

No, There is an existing code you need to add-on that

**Comment by SarthakKeshari** [comment]
Hey @Rishika631,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\metricUnitConverter

#### Be careful, do not break the old code that already exists.

Issue completion deadline - 24th Oct 8:00:00 am IST


*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Rishika631** [comment]
okay I will contribute the code under this file. I will surely keep check on not breaking the old code. Thank you for assigning it to me.

**Comment by Rishika631** [comment]
I have raised a PR. Please check and do let me know if any changes are needed then. I'll be happy to make changes.
