### ISSUE TITLE
operations on fractions 

### ISSUE THREAD

**Issue by dvtushar** [SarthakKeshari/calc_for_everything#215]
### Enter calculator name - 
operations on fractions 

### Describe calculator functionality - 
it will do mathematical operations like addition,subtraction,multiplication,divison on fractions.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by dvtushar** [comment]
kindly assign me this issue.

**Comment by SarthakKeshari** [comment]
Hey @dvtushar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\operationsOnFractions

Issue completion deadline - 13th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
