### ISSUE TITLE
Pythagoras Theorem

### ISSUE THREAD

**Issue by DanishGBU** [SarthakKeshari/calc_for_everything#216]
### Enter calculator name - 
Pythagoras Theorem

### Describe calculator functionality - 
The Pythagorean theorem is a cornerstone of math that helps us find the missing side length of a right triangle. In a right triangle with sides A, B, and hypotenuse C, the theorem states that A² + B² = C².

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by DanishGBU** [comment]
Kindly assign me this issue.

**Comment by SarthakKeshari** [comment]
Hey @DanishGBU,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\pythagorasTheorem

Issue completion deadline - 11th Oct 4:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
