### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#22]
### Enter calculator name - 
BMI Calculator

### Describe calculator functionality - 
You may refer - https://www.calculator.net/bmi-calculator.html

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[x] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Sam-bhav-20** [comment]
Hey @SarthakKeshari please assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @Sam-bhav-20,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\BMI

Issue completion deadline - 3rd Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by uttkarsh1m** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @uttkarsh1m,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\BMI

Issue completion deadline - 4th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Vimal-Dubey** [comment]
hey @SarthakKeshari 
kindly assign it to me

**Comment by SarthakKeshari** [comment]
@Vimal-Dubey,
I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 
For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉
