### ISSUE TITLE
hamming distance

### ISSUE THREAD

**Issue by remonix** [SarthakKeshari/calc_for_everything#220]
### Enter calculator name - 
Hamming Distance 

### Describe calculator functionality - 
The Hamming distance between two integers is the number of positions at which the corresponding bits are different. It is not dependent on the actual values of xi and yi but only if they are equal to each other or not equal

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_
-

**Comment by remonix** [comment]
kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @remonix,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\hammingDistance

Issue completion deadline - 13th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Shariar-Hasan** [comment]
if the work is not done, can you assign it to me?

**Comment by SarthakKeshari** [comment]
Hey @Shariar-Hasan,
I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 
For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉

**Comment by Shariar-Hasan** [comment]
ok, thank you 😊

**Comment by SarthakKeshari** [comment]
Issue closed under PR #370
