### ISSUE TITLE
Print Squares and Cubes within a Range (max- 1000)

### ISSUE THREAD

**Issue by Upadhyay-Harshit** [SarthakKeshari/calc_for_everything#222]
### Enter calculator name - 
Print Squares and Cubes within a range

### Describe calculator functionality - 
It will print squares and cubes within a specific range (max- 1000)

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign me this Issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\squareAndCubeCalc

Issue completion deadline - 12th Oct 2:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
