### ISSUE TITLE
Data Storage Convertor Calculator

### ISSUE THREAD

**Issue by shrinidhihegde3** [SarthakKeshari/calc_for_everything#226]
### Enter calculator name - 
Data Storage Convertor Calculator

### Describe calculator functionality - 
Converts any type of data to the required data type, including conversions between bits, bytes, megabytes, etc.

### Under which category you wish to place it - 
- [X] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by shrinidhihegde3** [comment]
hey @SarthakKeshari kindly assign this issue to me..

**Comment by SarthakKeshari** [comment]
Hey @shrinidhihegde3,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\dataStorageConverter

Issue completion deadline - 13th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by shrinidhihegde3** [comment]
hey @SarthakKeshari i have subitted pr/mr pls check

**Comment by shrinidhihegde3** [comment]
@SarthakKeshari sorry for the inconvenience, i have added now pls check
