### ISSUE TITLE
Body Fat Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#23]
### Enter calculator name - 
Body Fat Calculator

### Describe calculator functionality - 
You may refer - https://www.calculator.net/body-fat-calculator.html

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[x] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Saksham-245** [comment]
Hi @SarthakKeshari can you assign this to me!. Also please specify the details.

**Comment by 7twik** [comment]
Hi @SarthakKeshari i can work on this issue

**Comment by SarthakKeshari** [comment]
Hey @Saksham-245,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\BodyFat

Issue completion deadline - 3rd Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Saksham-245** [comment]
Ok Sure Thank You! @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @7twik,
Good to see you active again. We are following first come first serve. If deadline is not met, then it can be assigned to a new participant.

Happy contributing🎉

**Comment by SarthakKeshari** [comment]
@Saksham-245, For details you may refer the link provided under "Describe calculator Functionality"

**Comment by Saksham-245** [comment]
@SarthakKeshari I have just one question Do I need to implement tab like functionality and gender specific also.

**Comment by SarthakKeshari** [comment]
@Saksham-245, May you elaborate please.

**Comment by Saksham-245** [comment]
Like in the website it has tabs for US Units and Metric Units and in both units there is 2 radio buttons for gender male and female. Do I need to implement like that only or just One unit.

**Comment by SarthakKeshari** [comment]
@Saksham-245, Do the way you find it the most appropriate. I am ok.

**Comment by Saksham-245** [comment]
Ok Thanks!
