### ISSUE TITLE
Area of 2D Shapes (Rhombus, Trapezoid, Parallelogram, Ellipse, Arrow, Kite)

### ISSUE THREAD

**Issue by PrachiDev11** [SarthakKeshari/calc_for_everything#230]
### Enter calculator name - 
Area of 2D Shapes (Rhombus, Trapezoid, Parallelogram, Ellipse, Arrow, Kite)

### Describe calculator functionality - 
Here we will give the Area of above mentioned 2D shapes.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by PrachiDev11** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\areaOf2DShapes

Issue completion deadline - 12th Oct 8:00:00 am IST

#### Be careful, do not break the old code already exists. Old code was made as a part of - Number Type Finder I


*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @anushka-srivastava22,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\areaOf2DShapes

Issue completion deadline - 21th Oct 8:00:00 am IST

#### Be careful, do not break the old code already exists. Old code was made as a part of - #207 


*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@anushka-srivastava22,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 

### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\areaOf2DShapes

Issue completion deadline - 23th Oct 2:00:00 pm IST

#### Be careful, do not break the old code already exists. Old code was made as a part of - #207 


*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
As issue contains working with 6 calculators, I am upgrading the calculator label from easy -> medium.
