### ISSUE TITLE
Pressure Calculator

### ISSUE THREAD

**Issue by Rida-Nuha** [SarthakKeshari/calc_for_everything#231]
### Enter calculator name - 
Pressure Calculator

### Describe calculator functionality - 
With our pressure calculator, you can estimate the pressure exerted by a force on a specific surface area.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Rida-Nuha** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Rida-Nuha,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\pressureCalc

Issue completion deadline - 12th Oct 2:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
