### ISSUE TITLE
Surface Area of 3D Shape (Sphere, Cube, Cylinder, Cone, Pyramid)

### ISSUE THREAD

**Issue by PrachiDev11** [SarthakKeshari/calc_for_everything#232]
### Enter calculator name - 
Surface Area of 3D Shape (Sphere, Cube, Cylinder, Cone, Pyramid)

### Describe calculator functionality - 
Here, We will give the Surface Area of 3D Shapes of above mentioned shapes.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by PrachiDev11** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\surfaceAreaOf3DShapes

Issue completion deadline - 12th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by divyansh-4** [comment]
Hi @SarthakKeshari , I can get this done if it not completed yet.

**Comment by Harshit-Poddar90** [comment]
hello pls this task to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@divyansh-4 and @Harshit-Poddar90,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous issues are merged.

**Comment by anushka-srivastava22** [comment]
Kindly assign to me

**Comment by SarthakKeshari** [comment]
Hey @anushka-srivastava22,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\surfaceAreaOf3DShapes

Issue completion deadline - 21st Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@anushka-srivastava22,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 

### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\surfaceAreaOf3DShapes

Issue completion deadline - 23th Oct 2:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
