### ISSUE TITLE
Decimal/2421 code convertor

### ISSUE THREAD

**Issue by Upadhyay-Harshit** [SarthakKeshari/calc_for_everything#237]
### Enter calculator name - 
Decimal/2421 code convertor

### Describe calculator functionality - 
It is an unnatural BCD code. Sum of weights of unnatural BCD codes is equal to 9. It is a self-complementing code. Self-complementing codes provide the 9's complement of a decimal number, just by interchanging 1's and 0's in its equivalent 2421 representation.

### Under which category you wish to place it - 
- [X] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\dec2421CodeConverter

Issue completion deadline - 12th Oct 5:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
