### ISSUE TITLE
BMR calculator

### ISSUE THREAD

**Issue by 7twik** [SarthakKeshari/calc_for_everything#24]
### Enter calculator name - 
BMR calculator

### Describe calculator functionality - 
https://www.calculator.net/bmr-calculator.html

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[x] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by 7twik** [comment]
I opened this issue..and would love to work on it

**Comment by SarthakKeshari** [comment]
Hey @7twik,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\BMR

Issue completion deadline - 3rd Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
