### ISSUE TITLE
excess-3 code converter

### ISSUE THREAD

**Issue by munfaridzahera** [SarthakKeshari/calc_for_everything#240]
### Enter calculator name - 
excess-3 code converter

### Describe calculator functionality - 
the excess-3 code is a non-weighted code used to express code used to express decimal numbers.

### Under which category you wish to place it - 
- [x ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by munfaridzahera** [comment]
kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @munfaridzahera,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\excess3CodeConverter

Issue completion deadline - 13th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue was closed under PR #257
