### ISSUE TITLE
UI Upgradation For home and Landing page

### ISSUE THREAD

**Issue by Deathanni** [SarthakKeshari/calc_for_everything#244]
@SarthakKeshari ,

During my recent visit to the website, I encountered some challenges in utilizing the calculators. I found myself somewhat confused, and unable to access certain features due to the absence of clear guidance or instructions.

I kindly request the assignment of this issue to me so that I may work towards its resolution.

**Comment by SarthakKeshari** [comment]
Hey @Deathanni,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\UI_Docs

Issue completion deadline - 16th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by anushka-srivastava22** [comment]
Kindly assign the issue to me

**Comment by SarthakKeshari** [comment]
This issue was closed under PR #391
