### ISSUE TITLE
 UI Upgradation of Calculator Interfaces

### ISSUE THREAD

**Issue by Deathanni** [SarthakKeshari/calc_for_everything#245]
@SarthakKeshari ,

I kindly propose an upgrade for our calculator interfaces, as the current design appears outdated and disorganized. I am confident in my ability to improve it, and I request your consideration for this assignment.

**Comment by anushka-srivastava22** [comment]
Kindly assign the issue to me

**Comment by SarthakKeshari** [comment]
Hey @Deathanni,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\UI_Docs

Issue completion deadline - 19th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue was closed under PR #392
