### ISSUE TITLE
Converting to Roman Numerals

### ISSUE THREAD

**Issue by DanishGBU** [SarthakKeshari/calc_for_everything#246]
### Enter calculator name - 
Converting to Roman Numerals

### Describe calculator functionality - 
Roman Numerals is a special kind of numerical notation that was earlier used by the Romans. The Roman numeral is an additive and subtractive system in which letters are used to denote certain base numbers and arbitrary numbers in the number system.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by DanishGBU** [comment]
Kindly assign me to this issue.

**Comment by SarthakKeshari** [comment]
Hey @DanishGBU,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\romanNumeralConverter

Issue completion deadline - 13th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
