### ISSUE TITLE
Calc : EMI Calculator

### ISSUE THREAD

**Issue by prathimacode-hub** [SarthakKeshari/calc_for_everything#247]
### Enter calculator name - 

Calculating the EMI payment

### Describe calculator functionality - 

This feature request helps in calculating the EMI using principal amount, interest and time period given.

I would like to work on this issue under hacktoberfest. Can you assign me? @SarthakKeshari 

### Under which category you wish to place it - 

- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [x] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @prathimacode-hub and @TheShiveshNetwork,
Glad to see your eagerness for contributing 🤩.  This issue has already been addressed.
Hope to see you come up with more innovative issues.

Happy contributing!! 🎉

**Comment by prathimacode-hub** [comment]
@SarthakKeshari. Got you, thanks for the information. I had created a new issue here : https://github.com/SarthakKeshari/calc_for_everything/issues/251
