### ISSUE TITLE
Prime factors Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#25]
### Enter calculator name - 
Prime Factors

### Describe calculator functionality - 
Given a number as input by the user print all the prime factors of the number

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by dfordp** [comment]
can I be assigned this issue

**Comment by SarthakKeshari** [comment]
Hey @dfordp,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\prime_factors

Issue completion deadline - 3rd Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
