### ISSUE TITLE
Adding Info Tab to the calculator-Compound Interest,Prime Factors,Log and Anti Log, Quadratic Equations Solver

### ISSUE THREAD

**Issue by mr-kadyan** [SarthakKeshari/calc_for_everything#250]
**Is your feature request related to a problem? Please describe.**
Calculators do not have proper info

**Describe the solution you'd like**
Add Info Tab

**Comment by mr-kadyan** [comment]
Kindly Assign it to me

**Comment by SarthakKeshari** [comment]
Hey @mr-kadyan,
Assigned.

Issue completion deadline - 25th Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
