### ISSUE TITLE
Calc : Tip Calculator

### ISSUE THREAD

**Issue by prathimacode-hub** [SarthakKeshari/calc_for_everything#251]
### Enter calculator name - 

Calculator to Evaluate the Tip

### Describe calculator functionality - 

Tip Calculator takes the billing amount, type of service and a number of persons as input and generated the respective result for customers to pay the tip along with the bill amount.

I would like to work on this issue under hacktoberfest. Can you assign me? @SarthakKeshari 

### Under which category you wish to place it - 

- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [x] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @prathimacode-hub,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\tipCalc

Issue completion deadline - 14th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by prathimacode-hub** [comment]
Ok, thank you. Absolutely. @SarthakKeshari

**Comment by tejxv** [comment]
Since the deadline has passed and no PR has been committed, can i get assigned to this?

**Comment by prathimacode-hub** [comment]
I couldn't complete due to other work commitments. @SarthakKeshari, you can assign it to @tejxv

**Comment by SarthakKeshari** [comment]
Sure @prathimacode-hub

**Comment by SarthakKeshari** [comment]
Hey @tejxv,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\tipCalc

Issue completion deadline - 23rd Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
