### ISSUE TITLE
Number Type Finder (Fibonacci Number, Palindromic Number, Smith Number, Harshad Number, Happy Number) 

### ISSUE THREAD

**Issue by Sk783** [SarthakKeshari/calc_for_everything#255]
### Enter calculator name - 
Number Type Finder

### Describe calculator functionality - 
This versatile tool helps you explore the unique characteristics of any number you input. Whether it's identifying Fibonacci Numbers, Palindromic Numbers, Smith Numbers, Harshad Numbers, or Happy Numbers, this calculator provides a quick and intuitive way to classify and understand the properties of numbers. 

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Sk783** [comment]
Kindly assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Sk783,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\number_type_finder

#### Be careful, do not break the old code already exists.

Issue completion deadline - 14th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
