### ISSUE TITLE
Volume of 3D shapes (Prism, Torus, Ellipsoid, Cuboid)

### ISSUE THREAD

**Issue by ravishrivas** [SarthakKeshari/calc_for_everything#258]
### Enter calculator name - 
Volume of 3D shapes (Prism, Torus, Ellipsoid, Cuboid) Calculator

### Describe calculator functionality - 
Calculating the Volume of 3D shapes (Prism, Torus, Ellipsoid, Cuboid)

### Under which category you wish to place it - 
- [ ] Computer Science
- [x ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ravishrivas** [comment]
kindly assign it to me

**Comment by SarthakKeshari** [comment]
Hey @ravishrivas,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\volume3DShapes

Issue completion deadline - 14th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by divyansh-4** [comment]
Hi @SarthakKeshari , I see that deadline is over. In case this issue is not resolved yet, can I take this up ?
