### ISSUE TITLE
Log and Antilog Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#26]
### Enter calculator name - 
Log and Antilog

### Describe calculator functionality - 
Get a number and the base for log/antilog operation as input from the user and display log and antilog of the number.

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Sam-bhav-20** [comment]
hey @SarthakKeshari 
kindly assign me this

**Comment by SarthakKeshari** [comment]
Hey @Sam-bhav-20,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\log_antilog

Issue completion deadline - 3rd Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Sam-bhav-20** [comment]
@SarthakKeshari is it necessary to use material ui or i can go with simple divs also?

**Comment by SarthakKeshari** [comment]
@Sam-bhav-20, Simple divs will also do, but make sure not to use any other UI library.

**Comment by Sam-bhav-20** [comment]
okay thanks @SarthakKeshari

**Comment by Sam-bhav-20** [comment]
please help in merging this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hi @Sam-bhav-20, Let connect on PR #30 comment section.
