### ISSUE TITLE
Temperature Conversion Calculator (°C,°F, K)

### ISSUE THREAD

**Issue by chinmayr633** [SarthakKeshari/calc_for_everything#260]
### Enter calculator name - 
Temperature Converter

### Describe calculator functionality - 
coversion of temperature between Celsius ,Fahrenheit and kelvin

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by chinmayr633** [comment]
@SarthakKeshari  Please assign me this issue

**Comment by SarthakKeshari** [comment]
@chinmayr633,
May you add time coversion(ms, s, min, hours) too to the same calc?

**Comment by chinmayr633** [comment]
@SarthakKeshari  sure i will add time conversion also..

**Comment by SarthakKeshari** [comment]
Hey @chinmayr633,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\metricUnitConverter

Issue completion deadline - 15th Oct 8:00:00 am IST
#### Be careful, do not break the old code that already exists.

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by rishirohilla** [comment]
i would like to work on this issue , please assign me @SarthakKeshari

**Comment by chinmayr633** [comment]
Permission to SarthakKeshari/calc_for_everything.git denied to chinmayr633. I am getting this error while pushing commit changes

**Comment by SarthakKeshari** [comment]
@chinmayr633,

I see you haven't forked the repo, first do that then follow the below steps.

Run the following commands - 
git remote remove origin 
git remote add origin URL_OF_YOUR_REPO 
git push origin master
