### ISSUE TITLE
Upgrading dec to bin (vice versa) and hex to bin (vice versa) convertor (for floating point values)

### ISSUE THREAD

**Issue by dvtushar** [SarthakKeshari/calc_for_everything#264]
### Enter calculator name - 
dec to bin

### Describe calculator functionality - 
Upgrading dec to bin (vice versa) and hex to bin (vice versa) convertor (for floating point values)

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by dvtushar** [comment]
kindly assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @dvtushar,
Assigned.

You may contribute your code under the following folder paths -
### calc_for_everything\calculators\src\computer_science\DecToBinAndBinToDec
### calc_for_everything\calculators\src\computer_science\HexToBinAndBinToHex

#### Be careful, do not break the old code already exists.

Issue completion deadline - 14th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
