### ISSUE TITLE
CosmoMassConverter

### ISSUE THREAD

**Issue by chinmayr633** [SarthakKeshari/calc_for_everything#266]
### Enter calculator name - 
CosmoMassConverter

### Describe calculator functionality - 
Converts masses between various units  and calculates the body weight based on different planets...

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by chinmayr633** [comment]
@SarthakKeshari Please assign me this issue..

**Comment by SarthakKeshari** [comment]
Hey @chinmayr633,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\cosmoMassConverter

Issue completion deadline - 15th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
