### ISSUE TITLE
Day Scheduler

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#274]
### Enter calculator name - 
Day Scheduler

### Describe calculator functionality - 
The scheduler should allow the user to plan his day and download a copy of his schedule.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [x] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Heramb4270** [comment]
@SarthakKeshari what timings it must include i.e 8am to 10pm or the timing should given input by user ?

**Comment by SarthakKeshari** [comment]
Like it will be a 24 hrs clock, and user can set time slots according to his convenience.

Example -
8 am to 8:30 am - 
Breakfast

8:30 am to 9:30 am
Study

and so on

**Comment by Ayush-Vish** [comment]
@SarthakKeshari   I would like to work on this interesting issue.  Please assign me this issue.

**Comment by SarthakKeshari** [comment]
Hey @Ayush-Vish,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\dayScheduler

Issue completion deadline - 16th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
