### ISSUE TITLE
Mandala Creator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#275]
### Enter calculator name - 
Mandala Creator

### Describe calculator functionality - 
Take required inputs from the user. And create mandala in real time.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [x] Suggest a new category - _Art_

**Comment by nipun221** [comment]
@SarthakKeshari please assign me this issue. And kindly provide an extended deadline for the same.

**Comment by SarthakKeshari** [comment]
Hey @nipun221,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\art\mandalaCreater

Issue completion deadline - 18th Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by nipun221** [comment]
@SarthakKeshari I am working on it. Kindly, increase the deadline

**Comment by SarthakKeshari** [comment]
Hey @nipun221,
Issue completion deadline increased - 22nd Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue is closed with PR - #445
