### ISSUE TITLE
Congruency of Triangle Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#276]
### Enter calculator name - 
Congruency of Triangle Calculator

### Describe calculator functionality - 
Given required inputs by the user and check whether the two triangles are congruent or not.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by the-dg04** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @the-dg04,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\congruencyOfTriangleCalc

Issue completion deadline - 15th Oct 10:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @syash7202,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\congruencyOfTriangleCalc

Issue completion deadline - 24th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
