### ISSUE TITLE
Numerals to Words

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#277]
### Enter calculator name - 
Numerals to Words

### Describe calculator functionality - 
This calculator will take input as number from the user and present it in Indian and International System as well as write the numerals in word in both Indian and International System.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by plon-Susk7** [comment]
Hi I'd like to work on this issue, could you please assign me this?

**Comment by SarthakKeshari** [comment]
Hey @plon-Susk7,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\numeralsToWords

Issue completion deadline - 15th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by plon-Susk7** [comment]
Thanks @SarthakKeshari
