### ISSUE TITLE
Avatar Creator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#278]
### Enter calculator name - 
Avatar Creator

### Describe calculator functionality - 
Take required input from user and create Avatar for them.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [x] Suggest a new category - _Art_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign this to me

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\art\avatarCreater

Issue completion deadline - 23rd Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
