### ISSUE TITLE
Similarity of Triangle Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#279]
### Enter calculator name - 
Similarity of Triangle Calculator

### Describe calculator functionality - 
Given required inputs by the user, check whether the two triangles are similar or not.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Satvik-Garg** [comment]
@SarthakKeshari Kindly assign this issue to me

**Comment by rishirohilla** [comment]
kindly asign me this issue

**Comment by SarthakKeshari** [comment]
Hey @rishirohilla,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\similarityOfTriangleCalc

Issue completion deadline - 16th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by rishirohilla** [comment]
@SarthakKeshari I have made PR of issue #281 , i am waiting for you to merge that PR , then i will make PR of this issue.

**Comment by SarthakKeshari** [comment]
@rishirohilla,
I have provided my comments on the PR. Kindly check.
