### ISSUE TITLE
Quadratic equation Solver

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#28]
### Enter calculator name - 
Quadratic equation Solver

### Describe calculator functionality - 
Given coefficients of x^2, x and constant by the user, resolve the quadratic equation.

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by shreyashsingh-101** [comment]
Please Assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @shreyashsingh-101,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\quadratic_equation_solver

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
