### ISSUE TITLE
Chemical Formula Validator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#280]
### Enter calculator name - 
Chemical Formula Validator

### Describe calculator functionality - 
Propmt user to enter chemical formula like - H<sub>2</sub>O, etc. and display the output on the screen stating whether the formula is correct or not.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by sachinsingh2020** [comment]
Can you please assign me this task, I want to contribute

**Comment by SarthakKeshari** [comment]
Hey @sachinsingh2020,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\chemicalFormulaValidator

Issue completion deadline - 15th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue is closed under PR - #287
