### ISSUE TITLE
File/Data Comparator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#281]
### Enter calculator name - 
File/Data Comparator

### Describe calculator functionality - 
Allow the user to paste the content of the files in the text box provided and provide him the results based on the differences caught between the two files.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by rishirohilla** [comment]
Kindly assign me this issue @SarthakKeshari

**Comment by rishirohilla** [comment]
@SarthakKeshari i am waiting for  your response. Kindly look into it

**Comment by SarthakKeshari** [comment]
Hey @rishirohilla,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\fileDataComparator

Issue completion deadline - 16th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue was closed under PR #357
