### ISSUE TITLE
Task Planner

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#285]
### Enter calculator name - 
Task Planner

### Describe calculator functionality - 
Design task planner for the user for yearly, monthly or daily task planning as per the user requirement.
The planner would only list the task that needs to be done on that day, week or repeated over a period. 
It is NOT required to ask the user to designate a time in hours, minutes or seconds for the task. 
 
### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [x] Suggest a new category - _Lifestyle_

**Comment by uttkarsh1m** [comment]
hey @SarthakKeshari kindly assign it to me

**Comment by SarthakKeshari** [comment]
Hey @uttkarsh1m,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\taskPlanner

Issue completion deadline - 16th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @syash,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\taskPlanner

Issue completion deadline - 26th Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
