### ISSUE TITLE
BODMAS Equation Solver

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#29]
### Enter calculator name - 
BODMAS equation Solver

### Describe calculator functionality - 
Given a BODMAS equation as input first <b>check if its valid</b>, if valid solve and <b>display result</b>. And If Invalid display - <b>Invalid equation</b>.

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by imsoumik03** [comment]
hey @SarthakKeshari kindly assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @imsoumik03,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\bodmas_solver

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
