### ISSUE TITLE
Permutation and Combination calculator

### ISSUE THREAD

**Issue by Deathanni** [SarthakKeshari/calc_for_everything#291]
### Enter calculator name - 
Permutation and Combination calculator

### Describe calculator functionality - 
A permutation and combination calculator is a tool that calculates the number of ways you can arrange or select items from a set. It helps with:

Permutations: Calculating the number of arrangements.

Formula: P(n, r) = n! / (n - r)!
Input 'n' and 'r' to get the result.
Combinations: Calculating the number of selections.

Formula: C(n, r) = n! / (r! * (n - r)!)
Input 'n' and 'r' to get the result.
These calculators are useful in mathematics, statistics, and computer science for solving problems involving arrangements and selections of objects. They save time by automating complex calculations.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Deathanni** [comment]
@SarthakKeshari sir kindly assign me this issue

**Comment by Shubhgupta-coder** [comment]
sir pls assign it to me

**Comment by SarthakKeshari** [comment]
Hey @Shubhgupta-coder,
Glad to see your eagerness for contributing 🤩. But I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 

For now, kindly look into any open issues or you may even create one. 🤩🥳

Happy Contributing 🎉
