### ISSUE TITLE
Hamming Code

### ISSUE THREAD

**Issue by mr-kadyan** [SarthakKeshari/calc_for_everything#293]
### Enter calculator name - 
Hamming Code

### Describe calculator functionality - 
Hamming code is a type of error-correcting code used in digital communication and information storage systems to detect and correct errors that may occur during data transmission or storage.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by mr-kadyan** [comment]
Please assign me this issue.

**Comment by SarthakKeshari** [comment]
Hey @mr-kadyan,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\hammingCode

Issue completion deadline - 15th Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
