### ISSUE TITLE
Add Amplitude calculator

### ISSUE THREAD

**Issue by Ahasasjain** [SarthakKeshari/calc_for_everything#294]
### Enter calculator name - 
Amplitude calculator

### Describe calculator functionality - 
Calculator for finding amplitude, given distance traveled by wave (in Meters) and frequency (in Hertz).

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Ahasasjain** [comment]
please assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Ahasasjain,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\amplitudeCalc

Issue completion deadline - 16th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by MrDBC** [comment]
can i work on this issue ? @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @MrDBC,
Glad to see your eagerness for contributing 🤩. I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 

#### For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉

**Comment by SarthakKeshari** [comment]
Closed under #351
