### ISSUE TITLE
Upgrading oct to bin (vice versa) and dec to hex (vice versa) convertor for floating point values

### ISSUE THREAD

**Issue by Sk783** [SarthakKeshari/calc_for_everything#297]
### Enter calculator name - 
Octal to Binary and Binary to Octal
Decimal to Hexadecimal and Hexadecimal to Decimal

### Describe calculator functionality - 
The calculator converts floating point values from octal to binary, decimal to hexadecimal, and vice versa.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Sk783** [comment]
Kindly assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey ,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\OctToBinAndBinToOct
### calc_for_everything\calculators\src\computer_science\decToHexAndHexToDec

Issue completion deadline - 16th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Closing this issue with PR - #388
