### ISSUE TITLE
Documentation of - AND Operator, OR Operator and NOR Operator

### ISSUE THREAD

**Issue by Rida-Nuha** [SarthakKeshari/calc_for_everything#299]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Rida-Nuha,
Assigned.

Issue completion deadline - 16th Oct 6:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
