### ISSUE TITLE
GDP Calculator

### ISSUE THREAD

**Issue by Pratikdate** [SarthakKeshari/calc_for_everything#300]
### Describe calculator functionality - 

GDP= Personal consumption + Gross investment + government consumption + net exports of goods and services
GDP growth = (GDP in current period - GDP in the previous period) / GDP in the previous period × 100
GDP growth rate = (current GDP - previous GDP) / previous GDP.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [#] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Pratikdate** [comment]
assign me sir

**Comment by SarthakKeshari** [comment]
Hey @Pratikdate,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\gDPCalc

Issue completion deadline - 16th Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@Pratikdate,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @syash7202,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\gDPCalc

Issue completion deadline - 24th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
