### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#304]
### Enter calculator name - 
Random Number Generator

### Describe calculator functionality - 
Given a range, generate random number in that range on every user click.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
assign it to me

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\randomNumberGenerator

Issue completion deadline - 16th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
