### ISSUE TITLE
Graph Maker

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#31]
### Enter calculator name - 
Graph Maker

### Describe calculator functionality - 
Given an equation display the graph for it.

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by imsoumik03** [comment]
hey @SarthakKeshari , kindly assign me this issue . ☺️☺️☺️☺️

**Comment by D-Aman-S** [comment]
hey @SarthakKeshari  can you assign this me.Would love to implement this

**Comment by SarthakKeshari** [comment]
Hey @D-Aman-S,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉

**Comment by D-Aman-S** [comment]
@SarthakKeshari Thankyou so much for the beautiful clarification, I will look through the other issues.

**Comment by imsoumik03** [comment]
@SarthakKeshari  may I use an external package `chart.js` for easy code & better experiences.
