### ISSUE TITLE
Documentation of Bodmas Solver, Quadratic Eq Solver and Percentage Calculator 

### ISSUE THREAD

**Issue by girisha-pawan** [SarthakKeshari/calc_for_everything#313]
Kindly assign to me

**Comment by SarthakKeshari** [comment]
Hey @girisha-pawan,
Assigned.

Issue completion deadline - 17th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue is closed under PR - #432
