### ISSUE TITLE
Documentation of - Pressure Calculator, PH Calculator and Random Number Generator

### ISSUE THREAD

**Issue by Rida-Nuha** [SarthakKeshari/calc_for_everything#316]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Rida-Nuha,
Assigned.

Issue completion deadline - 17th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by abhijha1** [comment]
Kindly assign
