### ISSUE TITLE
Sum of N terms of Arithmetic Progression

### ISSUE THREAD

**Issue by ravishrivas** [SarthakKeshari/calc_for_everything#319]
### Enter calculator name - 
Sum of N terms of Arithmetic Progression

### Describe calculator functionality - 
It calculates the Sum of N terms of Arithmetic Progression
### Under which category you wish to place it - 
- [ ] Computer Science
- [x ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ravishrivas** [comment]
kindly assign it to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Kindly include all progressions like - AP, GP and HP

**Comment by shivanshhgit** [comment]
@SarthakKeshari I can implement calculator for sum of n terms for all 3 progressions.
Kindly assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @shivanshhgit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\sumAPGPHPCalc

Issue completion deadline - 22nd Oct 9:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
