### ISSUE TITLE
Set Operations

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#32]
### Enter calculator name - 
Set Operations

### Describe calculator functionality - 
Given two sets, perform following set operations -
- Union of sets
- Intersection of sets
- Complement of a set
- Difference between sets/Relative Complement

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Satvik-Garg** [comment]
hi @SarthakKeshari 
kindly assign this issue to me under Hacktoberfest2023 . I'll try my best to resolve the issue

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\set_operations

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
