### ISSUE TITLE
ML data cleaner

### ISSUE THREAD

**Issue by dvtushar** [SarthakKeshari/calc_for_everything#321]
### Enter calculator name - 
ml data cleaner
### Describe calculator functionality - 
this will clean and filter your csv files (you can see the filtered data in console.log currently)

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by dvtushar** [comment]
kindly assign me this issue :)

**Comment by SarthakKeshari** [comment]
Hey @dvtushar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\dataCleaner

Issue completion deadline - 17th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
