### ISSUE TITLE
Checksum calculator

### ISSUE THREAD

**Issue by Upadhyay-Harshit** [SarthakKeshari/calc_for_everything#323]
### Enter calculator name - 
Checksum calculator

### Describe calculator functionality - 
The purpose of a checksum is to detect errors or changes in the data during transmission or storage.

### Under which category you wish to place it - 
- [X] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\checksumCalc

Issue completion deadline - 18th Oct 9:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
