### ISSUE TITLE
IP Address Numerical - Broadcast ID, Network Address, Class, Last usable host address.

### ISSUE THREAD

**Issue by Upadhyay-Harshit** [SarthakKeshari/calc_for_everything#324]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\iPAddressCalc

Issue completion deadline - 18th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
