### ISSUE TITLE
IP Address calculator

### ISSUE THREAD

**Issue by dvtushar** [SarthakKeshari/calc_for_everything#325]
### Enter calculator name - 
IP Address Numerical calculator
### Describe calculator functionality - 
this will tell the following:
First address
Last address
Subnet Mask
Complement subnet mask
Unique ID (host) number

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by dvtushar** [comment]
kindly assign me this issue :)

**Comment by SarthakKeshari** [comment]
Hey @dvtushar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\iPAddressCalc

Issue completion deadline - 18th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
