### ISSUE TITLE
Pic Editor

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#326]
### Enter calculator name - 
Pic Editor

### Describe calculator functionality - 
Add 2 to 3 basic pic editor tool for the user

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Art
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign this to me

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\art\picEditor

Issue completion deadline - 23rd Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by tejxv** [comment]
since the deadline has passed, can i get this issue?

**Comment by SarthakKeshari** [comment]
@Upadhyay-Harshit,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @tejxv,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\art\picEditor

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by ShivamPatel-24** [comment]
@SarthakKeshari Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
@tejxv,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @ShivamPatel-24,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\art\picEditor

Issue completion deadline - 06th Dec  02:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
