### ISSUE TITLE
Paragraph Summarizer

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#327]
### Enter calculator name - 
Paragraph Summarizer

### Describe calculator functionality - 
Give a paragraph by the user summarize it.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by uttkarsh1m** [comment]
hey @SarthakKeshari kindly assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @uttkarsh1m,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\paraSummarizer

Issue completion deadline - 18th Oct 9:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by uttkarsh1m** [comment]
hey @SarthakKeshari i have already solved this issue . Please merge the pr of the issue #203 then i will make the pr of this issue.

**Comment by SarthakKeshari** [comment]
@uttkarsh1m,
Thanks for informing. I have merged the previous PR kindly go ahead with this.
