### ISSUE TITLE
Images to PDF consolidator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#328]
### Enter calculator name - 
Images to PDF consolidator

### Describe calculator functionality - 
Take 1 or more image from the user and make a pdf of it

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Shival-Gupta** [comment]
Please assign this task to me

**Comment by SarthakKeshari** [comment]
Hey @Shival-Gupta,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\imagesToPDFConsolidator

Issue completion deadline - 19th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Shival-Gupta** [comment]
Hi @SarthakKeshari

It seems there was a misunderstanding about the deadline for this issue. I had requested the task to be assigned on the 20th, so the deadline mentioned for the 19th is incorrect. 

Please update the deadline accordingly. 

Thank you!

**Comment by SarthakKeshari** [comment]
@Shival-Gupta,
Thanks for informing.

**Comment by tejxv** [comment]
since the deadline has passed and no PR has been made, can i get assigned to this?

**Comment by SarthakKeshari** [comment]
@Shival-Gupta,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @tejxv,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\imagesToPDFConsolidator

Issue completion deadline - 25th Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Closed this issue under the PR - #503
