### ISSUE TITLE
Image Text Reader

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#329]
### Enter calculator name - 
Image Text Reader

### Describe calculator functionality - 
Provided an image by the user, extract the text out of it.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @divyansh-4,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\imageTextReader

Issue completion deadline - 18th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Shashankpantiitbhilai** [comment]
assign this to me

**Comment by divyansh-4** [comment]
HI @SarthakKeshari, I have opened a pull request for this.
I had a few ideas, which I could implement for this if you were fine with them and I could work on it under another issue:
1. Hindi Image to Text.
2. Rich Text Editor for the text received from image
3. Automatic PDF Generator for Text Generated from Image

KIndly do let me know of you woudl like me to create a new issue and work on them.
