### ISSUE TITLE
Quadratic Eq. Intersection Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#33]
### Enter calculator name - 
Quadratic Eq. Intersection Calculator

### Describe calculator functionality - 
Given two quadratic equations, find whether they will <b>intersect or not</b>, if <b>yes</b> display the intersection points. And if <b>not</b>, display - "Equations do not intersect"

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Sam-bhav-20** [comment]
Hey @SarthakKeshari 
kindly give me this issue

**Comment by SarthakKeshari** [comment]
@Sam-bhav-20,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous issues are merged.

**Comment by Sam-bhav-20** [comment]
kindly merge the previous issue i have fixed that #26 Log and Antilog Calculator

**Comment by SarthakKeshari** [comment]
@Sam-bhav-20, I have provided review comments. Kindly work on that.

**Comment by Sam-bhav-20** [comment]
i didn't get anything @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Kindly check the PR #30

**Comment by DeexithParand2k2** [comment]
I'd like to work on this issue. Could you please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @DeexithParand2k2,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\quadratic_eq_intersection

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by DeexithParand2k2** [comment]
Sure @SarthakKeshari I'll do it and let you know.

**Comment by DeexithParand2k2** [comment]
hi @SarthakKeshari  I've completed working on the issue "Quadratic Equation Intersection Calculator" within the specified deadline. Kindly accept and merge my PR as soon as possible. Thank you so much for the opportunity.
