### ISSUE TITLE
DNA - RNA Converter

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#334]
### Enter calculator name - 
DNA - RNA Converter

### Describe calculator functionality - 
DNA - RNA converter takes the four nucleobase chemical structure pairs of DNA as input and gives its corresponding nucleobase chemical structure of RNA as output and vice-versa.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [x] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\biology\dNARNAConverter

Issue completion deadline - 25th Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
