### ISSUE TITLE
RMS value Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#336]
### Enter calculator name - 
RMS value Calculator

### Describe calculator functionality - 
RMS value Calculator takes a function f(x) and the range of f(x) is defined ; and calculates the RMS value of the Fourier in that range.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ravishrivas** [comment]
kindly assign it to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
This issue has been closed under PR- #506
