### ISSUE TITLE
Factorial Calculator ( Gamma )

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#337]
### Enter calculator name - 
Factorial Calculator ( Gamma )

### Describe calculator functionality - 
The Calculator takes an input ( fraction, rational, irrational, etc. ) and calculates the factorial of the input using gamma functions of sine and cosine.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ctln23** [comment]
@Vedansh-Keshari, I would like t work on this. Kindly assign this to me

**Comment by ctln23** [comment]
@Vedansh-Keshari, I would like to work on this. Kindly, assign it to me

**Comment by SarthakKeshari** [comment]
Hey @ctln23,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\factorialCalc_Gamma

Issue completion deadline - 22nd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
