### ISSUE TITLE
Partial Fractions Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#338]
### Enter calculator name - 
Partial Fractions Calculator

### Describe calculator functionality - 
Partial Fractions Calculator takes an input f(x) , analyses it, and then breaks it down into terms which are singular fractions by the method of Partial Fractions.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Please assign it to me

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\partialFractionsCalc

Issue completion deadline - 29th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@Upadhyay-Harshit,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @syash7202,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\partialFractionsCalc

Issue completion deadline - 31st Oct 08:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue is closed under PR - #618
