### ISSUE TITLE
Vibrational Response Calculator

### ISSUE THREAD

**Issue by VincentPaulV** [SarthakKeshari/calc_for_everything#339]
### Enter calculator name - 
Vibrational Response Calculator

### Describe calculator functionality - 
In this calculator, I would like to implement the following:
1. Take the user input for the system parameters, such as mass and stiffness.
2. Ask the user to choose an excitation mode.
3. Give the user the response of the system to the excitation mode in terms of displacement, velocity, acceleration.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by lunoos** [comment]
Hey I would like to work on this enhancement can you please assign it to me under hactoberfest tag.

**Comment by VincentPaulV** [comment]
> Hey I would like to work on this enhancement can you please assign it to me under hactoberfest tag.

Hey, there @lunoos!!
I'm not the author of this repository so I can't assign this issue to you.

I in fact raised this issue as a contributor and I thought of contributing to this repository.

You too could raise an issue that contains your idea and can contribute to this repository
All the best!!

**Comment by SarthakKeshari** [comment]
Hey @VincentPaulV,
In order to get the issue assigned kindly leave a comment for example - "Kindly assign it to me" or "Hey, I wish to work on this", as per the contribution guidelines.

Hope to go by the books for the contributions 😊

Happy Contributing!! 🎉

**Comment by VincentPaulV** [comment]
Sure, I'll do that

**Comment by VincentPaulV** [comment]
Hey, I wish to work on this @SarthakKeshari
Could you assign this issue to me?
Thanks!!

**Comment by SarthakKeshari** [comment]
@VincentPaulV,
Going by the rules set for the repo, I will be assigning it to @lunoos for now. 
In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b>

Hope to have your innovative inputs and enthusiastic contributions. I remember your contributions to the repository. Thanks for making it more valuable.

**Comment by SarthakKeshari** [comment]
Hey @lunoos,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\vibrationalResponseCalc

Issue completion deadline - 18th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by VincentPaulV** [comment]
Sure. That's totally acceptable.
Thanks for making a fair decision. 

I've opened a new issue and have followed the contribution guidelines there.
I hope that I can continue my contribution to this repository through that issue!

Thanks!!

**Comment by SarthakKeshari** [comment]
@lunoos,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari !!
I had already been assigned 2 issues by the time this issue had been unassigned.

I have raised the PR for one of my issues assigned already, so I have a slot for 1 more issue as per the contributing guidelines.

If it's available could you please assign me this issue?
Thanks!!

**Comment by VincentPaulV** [comment]
Can you assign this issue to me @SarthakKeshari ?

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari!
Thanks for the assignment of the issue.
A tiny request from my end to make this a hard issue and give some more time on this because I personally believe it is very complicated conceptually and presenting the output may involve calculating various terms.

Thanks!!

**Comment by SarthakKeshari** [comment]
@VincentPaulV,
I will extend the time. But to make it a hard issue. I need to re-think and discuss with my collaborator.
I will get back on this within 24 hrs.

**Comment by SarthakKeshari** [comment]
Deadline updated - 27th Oct 11:00:00 pm IST

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari !!

Any updates on the issue difficulty here?
If necessary I'd also like to tell you my approach to making this calculator so that it may help in your decision making.

Thanks!!

**Comment by SarthakKeshari** [comment]
@VincentPaulV,
I have revisited the calculator and its calculation and am of the opinion to make it `medium` issue.
And yes, I welcome your explanation. Kindly go ahead.

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari !!
Really sorry for these repetitive requests from my end nowadays but if you don't mind could you postpone the deadline to tomorrow evening (I promise this is my last request) as I'm caught up with some work today.

Regarding the idea of implementation I'll give it to you by today evening to justify my request for the difficulty change.

Thanks.

**Comment by SarthakKeshari** [comment]
@VincentPaulV,
I really appreciate your responsible communication, and this will increase the deadline by 48 hrs more.
Updated Deadline - 29th Oct 11:00:00 pm IST

**Comment by SarthakKeshari** [comment]
@VincentPaulV,
I see that you have really put in a lot of effort as well as you have added a clear visualization for the result. Hence, considering and respecting your words on the complexity of this calculator, I am upgrading the calculator again from `medium -> hard`. Issue - #339.

As well as I am glad to see such dedication towards issue resolution as well as appreciate the fact that you came forward to discuss on the complexity of the calculator, hence helping me with decision making for this issue. I am further adding admin-appreciation points to the PR - #546.
