### ISSUE TITLE
Linear Eq. Intersection Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#34]
### Enter calculator name - 
Linear Eq. Intersection Calculator

### Describe calculator functionality - 
Given two linear equations, find whether they will <b>intersect or not</b>, if <b>yes</b> display the intersection points. And if <b>not</b>, display - "Lines are parallel, so do not intersect"

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by rishirohilla** [comment]
Kindly Give me this issue @SarthakKeshari

**Comment by rishirohilla** [comment]
Kindly assign me this this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @rishirohilla,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\linear_eq_intersection

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
