### ISSUE TITLE
Homogeneous Interpreter

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#342]
### Enter calculator name - 
Homogenous Interpreter

### Describe calculator functionality - 
Provided any Difference Equation or given function and checking whether it is homogeneous or NOT .

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by sikehish** [comment]
I'd like to work on this

**Comment by sikehish** [comment]
Sure @SarthakKeshari , will complete it and update very soon :)

**Comment by SarthakKeshari** [comment]
Hey @Rishika631,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\homogeneousInterpreter

Issue completion deadline - 25th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Rishika631** [comment]
I have raised a PR for this issue.
