### ISSUE TITLE
Differential Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#343]
### Enter calculator name - 
Differential Calculator

### Describe calculator functionality - 
Given a function F(x) of the degree y'' , the Differential Calculator showcases the Auxiliary Equation, Complementary function and the Particular Integral and thus finds the roots of the Differential of F(x)

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by nipun221** [comment]
@SarthakKeshari @Vedansh-Keshari  kindly assign me this issue.

**Comment by SarthakKeshari** [comment]
Hey @nipun221,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\differentialCalc

Issue completion deadline - 21th Oct 10:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
