### ISSUE TITLE
IEEE754 Converter

### ISSUE THREAD

**Issue by XronTrix10** [SarthakKeshari/calc_for_everything#344]
### Enter calculator name - 
IEEE Standard 754 Floating Point Converter

### Describe calculator functionality - 
Input a number in decimal system and get the IEEE 754 Standard Single precision representation of the number in both 32bit and 64bit

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by XronTrix10** [comment]
@SarthakKeshari I want to add this calculator. Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @XronTrix10,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\iEEE754Converter

Issue completion deadline - 18th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Shashankpantiitbhilai** [comment]
assign this to me
