### ISSUE TITLE
Satellite Location using TLE

### ISSUE THREAD

**Issue by divyansh-4** [SarthakKeshari/calc_for_everything#345]
### Enter calculator name - 
Satellite Latitude, longitude using TLE

### Describe calculator functionality - 
Given a satellite's TLE, return the latitude, longitude and country. 
Can even be extended to plot the satellite on a map.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [x] Suggest a new category - _Space_

**Comment by divyansh-4** [comment]
HI @SarthakKeshari , I'd like to add this feature under Haktoberfest. Can you please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @divyansh-4,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\space\satelliteLocationUsingTLE

Issue completion deadline - 19th Oct 9:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by divyansh-4** [comment]
Hi @SarthakKeshari ,
I have opened a new PR for this issue. KIndly do let me know if can help you out more on this issue.
Thank You !
