### ISSUE TITLE
Adding New Density Calculator

### ISSUE THREAD

**Issue by Pasqua101** [SarthakKeshari/calc_for_everything#346]
### Enter calculator name - 
Density Calculator

### Describe calculator functionality - 
The functionality of the calculator will be to use to equation p = m/v. With p being density, m being mass and v being volume. Mass will be in kilograms, and volume with be in cubic meters m<sup>3</sup>. This will return a value of kilograms/cubic meter (kg/m<sup>3</sup>) for the density. 

Additionally, I will be adding this calculator name to the README.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Pasqua101** [comment]
Could you kindly assign this issue to me with the label of hacktoberfest?

**Comment by SarthakKeshari** [comment]
Hey @Pasqua101,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\densityCalc

Issue completion deadline - 19th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Pasqua101** [comment]
@SarthakKeshari Thank you. I have created the pull request for the calculator. Please let me know what you think. Also, I noticed some spelling errors, and/or formatting inconsistencies within the README.md  and CONTRIBUTING.md files. Would you like me to make a separate issue for this problem or make those changes in this issue as well?
