### ISSUE TITLE
Sum of N terms in an AP, GP, HP

### ISSUE THREAD

**Issue by VincentPaulV** [SarthakKeshari/calc_for_everything#347]
### Enter calculator name - 
Sum of N terms in an AP, GP, HP

### Describe calculator functionality - 
I would like to implement the following:
1. Take the user input for initial term, d/r term and n.
2. Use the formulae and give the user an output
3. I will give the output to the user on the basis of the computed result.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by VincentPaulV** [comment]
I'd like to take up this issue @SarthakKeshari!

**Comment by VincentPaulV** [comment]
Hey, I wish to work on this @SarthakKeshari
Could you assign this issue to me?
Thanks!!

**Comment by VincentPaulV** [comment]
Hey @SarthakKeshari !
Just wanted to know the status of this issue, is there going to be any assignment of this issue?
Thanks!!

**Comment by SarthakKeshari** [comment]
@VincentPaulV,
There is already a similar issue open.
