### ISSUE TITLE
Molecular Weight Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#350]
### Enter calculator name - 
Molecular Weight Calculator

### Describe calculator functionality - 
Known the atomic weights of the elements of the compound, the Molecular Weight Calculator as the name suggests calculates the weight of the chemical compound provided, it is valid.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Satvik-Garg** [comment]
Kindly assign it to me

**Comment by SarthakKeshari** [comment]
This issue has already been covered.
