### ISSUE TITLE
Empirical Formula Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#352]
### Enter calculator name - 
Empirical Formula Calculator

### Describe calculator functionality - 
Empirical Formula Calculator calculates the Empirical formula of any given molecule and displays the ratio of the elements present in that compound.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ravishrivas** [comment]
kindly assign it to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @ravishrivas,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\empiricalFormulaCalc

Issue completion deadline - 22nd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
