### ISSUE TITLE
MKS - CGS - FPS

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#353]
### Enter calculator name - 
System of Units Converter

### Describe calculator functionality - 
The System of Units Converter takes a value in either of the Si unit standards and converts it into the other two Si unit standards.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by rishirohilla** [comment]
Kindly assign it to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @rishirohilla,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\mKSCGSFPSCalc

Issue completion deadline - 22nd Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@rishirohilla,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by aditya962** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @aditya962,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\mKSCGSFPSCalc

Issue completion deadline - 22nd Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue has been closed under PR - #511
