### ISSUE TITLE
Projectile Motion Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#354]
### Enter calculator name - 
Projectile Motion Calculator

### Describe calculator functionality - 
The Projectile Motion Calculator takes and provides the values like velocity, angle of Projection, initial height, Vx, Vy, gravitational acceleration, Time of Flight, Range, Hmax (maximum vertical height), and other essential factors and changes one with respect to the other in real time, without clicking the calculate button.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @imsoumik03,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\projectileCalc

Issue completion deadline - 19th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
