### ISSUE TITLE
Combined Gas Laws Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#355]
### Enter calculator name - 
Combined Gas Laws Calculator

### Describe calculator functionality - 
Combined Gas Laws Calculator works on the principle of Gas Laws by Boyle's Charle's Gay-Lussac's and Avogadro's. The calculator should be able to deal with each of them separately or a combination of these, or all combined. Inputs : P(pressure) , V(Volume) and T(Temperature) ; Output : kB (gas constant).

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Satvik-Garg** [comment]
Kindly assign it to me

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\combinedGasLawsCalc

Issue completion deadline - 22nd Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@Satvik-Garg,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by Rida-Nuha** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Rida-Nuha,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\combinedGasLawsCalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
