### ISSUE TITLE
Ohm's Law Calculator

### ISSUE THREAD

**Issue by vidip21** [SarthakKeshari/calc_for_everything#356]
### Enter calculator name - 
Ohm's Law calculator

### Describe calculator functionality - 
An Ohm's Law calculator is a tool that quickly computes voltage, current, or resistance in electrical circuits using the fundamental formula V = I * R, aiding in circuit analysis and design.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by vidip21** [comment]
Can you please assign it to me

**Comment by SarthakKeshari** [comment]
Hey @vidip21,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\ohmsLawCalc

Issue completion deadline - 19th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@vidip21,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @syash7202,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\ohmsLawCalc

Issue completion deadline - 19th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
