### ISSUE TITLE
Temperature converter

### ISSUE THREAD

**Issue by Skb08** [SarthakKeshari/calc_for_everything#358]
### Enter calculator name - 
Temperature Converter

### Describe calculator functionality - 
temperature convert from (Celsius or Fahrenheit or Kelvin) to Celsius, Fahrenheit, Kelvin.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Skb08** [comment]
Can you assign me this under hacktoberfest.

**Comment by SarthakKeshari** [comment]
Hey @Skb08,
Glad to see your eagerness for contributing 🤩.  This issue has already been addressed in #260
Hope to see you come up with more innovative issues.

Happy contributing!! 🎉
