### ISSUE TITLE
MultiCurreny Change Calculaotr

### ISSUE THREAD

**Issue by chinmayr633** [SarthakKeshari/calc_for_everything#359]
### Enter calculator name - 
MultiCurreny Change Calculaotr

### Describe calculator functionality -
It allows users to effortlessly compute change in their preffered currency. 

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by chinmayr633** [comment]
@SarthakKeshari  please assign me this issue

**Comment by SarthakKeshari** [comment]
@chinmayr633,
May you elaborate more on the calculator's functionality

**Comment by chinmayr633** [comment]
It's a change calculator used in shopping mall or in any grocery store how much amount the shop keeper should give to the buyer like how much 100,50,10,1 Rs he should give . And also have function to change  user preferred currency.

**Comment by SarthakKeshari** [comment]
Hey @chinmayr633,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\multiCurrencyChangeCalc

Issue completion deadline - 22nd Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Reponing issue, due to correction in code.
