### ISSUE TITLE
Matrix Addition

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#36]
### Enter calculator name - 
Matrix Addition

### Describe calculator functionality - 
Take size of matrices as input from user then take two Matrices of the specified size as input and display the result of their addition.
### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari, I have a working knowledge of Javascript and really want to have the functionality of matrix operations in Javascript for some of my projects which involve calculating parameters for the simulation of physical systems on a canvas.

I would really like to contribute to this and I would not only want to stop here but also perform the other matrix operations.

I find this project extremely useful and would like to start off by contributing to GitHub.

Would love to hear back from you if you want to assign this issue to me.

Thanks :)

**Comment by SarthakKeshari** [comment]
Hey @VincentPaulV,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\matrix_addition

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari,

I have completed the Matrix Addition along with the Matrix subtraction and have committed it to a fork of this repository.
I'm kind of new to the contributor space so I'm not sure of what's to be done after this.
I would love to hear of what to do next.

Thanks!
