### ISSUE TITLE
Laplace Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#361]
### Enter calculator name - 
Laplace Calculator

### Describe calculator functionality - 
Laplace Calculator takes a function f(t) as input and abiding by the rules of Laplace Transforms converts it into the function f(s) and displays it as output

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ashishnallana** [comment]
hey @SarthakKeshari i would like to work on this.

**Comment by SarthakKeshari** [comment]
Hey @ashishnallana,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\laplaceCalc

Issue completion deadline - 22nd Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by ashishnallana** [comment]
@SarthakKeshari  can i try using an API to show the result.

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari  can i try using an API to show the result. (I tried writing code for laplace transformation, but it's too complex.)
> 

@ashishnallana,
Yes go ahead. I will review. I know its too complex.

**Comment by nipun221** [comment]
@SarthakKeshari Can i get this issue ?

**Comment by SarthakKeshari** [comment]
@ashishnallana,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @nipun221,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\laplaceCalc

Issue completion deadline - 25th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by nipun221** [comment]
@SarthakKeshari Kindly increase the deadline as i am working on it.

**Comment by SarthakKeshari** [comment]
Sure @nipun221,
Deadline updated - 28th Oct 11 pm IST
