### ISSUE TITLE
Pipes & Cisterns Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#365]
### Enter calculator name - 
Pipes & Cisterns Calculator

### Describe calculator functionality - 
The Pipes & Cisterns Calculator takes the number of taps and other variables (filling/emptying) as input and gives the time after which the cistern will be filled/emptied and half/full accordingly.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ashishnallana** [comment]
hey @SarthakKeshari i would like to work on it.

**Comment by SarthakKeshari** [comment]
Hey @ashishnallana,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\pipesAndCisternsCalc

Issue completion deadline - 22nd Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
