### ISSUE TITLE
Matrix Substraction

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#37]
### Enter calculator name - 
Matrix Substraction

### Describe calculator functionality - 
Take size of matrices as input from user then take two Matrices of the specified size as input and display the result of their substraction.
### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari, I would kind of like to do this along with Matrix Addition as I've mentioned as this is very similar to Addition and it'll be better if I could do it together.

Thanks :)

**Comment by SarthakKeshari** [comment]
Hey @VincentPaulV,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\matrix_substraction

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
