### ISSUE TITLE
Complement Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#373]
### Enter calculator name - 
Complement Calculator

### Describe calculator functionality - 
The Complement Calculator takes a number and the base in which the number is written, and then finds the nth complement of the number as per the input.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ctln23** [comment]
@Vedansh-Keshari, I would like to work on this. Kindly assign this to me

**Comment by its-kumar-yash** [comment]
@Vedansh-Keshari I want to work on this issue, please assign this to me

**Comment by SarthakKeshari** [comment]
Hey @its-kumar-yash,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\complementCalc

Issue completion deadline - 22nd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
