### ISSUE TITLE
Base Change Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#374]
### Enter calculator name - 
Base Change Calculator

### Describe calculator functionality - 
The Base Change Calculator takes a number N in the base n and converts it into a number M of base m. ( both being equal )
( the negative values for each may/may-not be handled )

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by its-kumar-yash** [comment]
@Vedansh-Keshari I want to work on this issue, Kindly assign this to me

**Comment by ctln23** [comment]
@Vedansh-Keshari, I can implement this calculator. Kindly assign this to me

**Comment by SarthakKeshari** [comment]
Hey @its-kumar-yash,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\baseChangeCalculator

Issue completion deadline - 22nd Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
