### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#377]
Quadratic Equations intersection 
Polynomial equations root finder
Set operations

**Comment by munfaridzahera** [comment]
Kindly assign it to me

**Comment by SarthakKeshari** [comment]
Hey @munfaridzahera,
Assigned.

Issue completion deadline - 21st Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
