### ISSUE TITLE
Matrix Multiplication

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#38]
### Enter calculator name - 
Matrix Multiplication

### Describe calculator functionality - 
Take size of matrices as input from user then take two Matrices of the specified size as input and display the result of their multiplication.
### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by tmsagarofficial** [comment]
Hey @SarthakKeshari , I would love to work on this issue. Pls assign it to me

**Comment by SarthakKeshari** [comment]
Hey @tmsagarofficial,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\matrix_multiplication

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by imnaseem** [comment]
If this issue remains unresolved, I would love to work on it.

**Comment by SarthakKeshari** [comment]
@imnaseem, Definitely, if the deadline is not met.
Kindly comment again, once the deadline is crossed.

**Comment by imnaseem** [comment]
If this issue continues without resolution, please assign it to me.

**Comment by tmsagarofficial** [comment]
My bad i had done the commit but forgot to make a PR 😓
