### ISSUE TITLE
POS - SOP Converter

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#381]
### Enter calculator name - 
POS - SOP Converter

### Describe calculator functionality - 
This Calculator takes the total number of different variables present in the expression. If a POS expression is provided, it converts it into an SOP and vice versa efficiently.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [x] Digital Systems Design
- [x] Microprocessors & Microcontrollers
- [ ] Suggest a new category - _(Answer here)_

**Comment by Satvik-Garg** [comment]
@SarthakKeshari kindly assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\pOSSOPConverter

Issue completion deadline - 22nd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
