### ISSUE TITLE
Gray Code Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#382]
### Enter calculator name - 
Gray Code Calculator

### Describe calculator functionality - 
The Gray Code Calculator takes either input in binary format and converts it into the Gray Code or vice-versa.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [x] Microprocessors & Microcontrollers
- [x] Digital Systems Design
- [ ] Suggest a new category - _(Answer here)_

**Comment by Satvik-Garg** [comment]
@SarthakKeshari kindly assign me this issue

**Comment by PrachiDev11** [comment]
kindly assign to me @SarthakKeshari @Vedansh-Keshari

**Comment by SarthakKeshari** [comment]
@Satvik-Garg,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous issues are merged.

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\grayCodeCalc

Issue completion deadline - 22nd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
