### ISSUE TITLE
MUX Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#384]
### Enter calculator name - 
MUX Calculator

### Describe calculator functionality - 
The MUX Calculator takes the value n as input for the number of Selection lines, and a binary String i , such that the length of i does not exceed the value n. The String i is to determine which input line entering the MUX will be taken forward to the output f .

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Microprocessors & Microcontrollers
- [x] Digital System Design
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by sikehish** [comment]
Im interested in working on this. Could you assign it to me

**Comment by SarthakKeshari** [comment]
Hey @sikehish,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\mUXCalc

Issue completion deadline - 23rd Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by sikehish** [comment]
Im working on it

**Comment by sikehish** [comment]
![image](https://github.com/SarthakKeshari/calc_for_everything/assets/90673701/50f9a912-aca4-47bd-91b1-b800656d0d82)
Hi @SarthakKeshari. Ive implemented it. Let me know if any changes are to be made :)
