### ISSUE TITLE
DeMUX Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#386]
### Enter calculator name - 
DeMUX Calculator

### Describe calculator functionality - 
The DeMUX Calculator takes the value n as input for the number of Selection lines, and an input f, which gives an output binary String i of length not exceeding the value of n. The String i is to determine which output line leaving the DeMUX will be chosen from the input f.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [x] Digital System Design
- [x] Microcontrollers & Microprocessors
- [ ] Suggest a new category - _(Answer here)_

**Comment by Rishika631** [comment]
Hello can you please assign me this

**Comment by SarthakKeshari** [comment]
Hey @Rishika631,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\deMUXCalc

Issue completion deadline - 23rd Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Rishika631** [comment]
okay. I'll try to complete it.

**Comment by Rishika631** [comment]
I have raised a PR please do check.
