### ISSUE TITLE
Transpose of Matrix

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#39]
### Enter calculator name - 
Transpose of Matrix

### Describe calculator functionality - 
Take size of matrix as input from user then take matrix of the specified size as input and display the transpose of the matrix.
### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Akash0420** [comment]
Kindly assign me this this issue @SarthakKeshari

**Comment by kittoteja** [comment]
can you please assign this to me

**Comment by SarthakKeshari** [comment]
Hey @Akash0420,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\matrix_determinant

Issue completion deadline - 4th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @kittoteja,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
