### ISSUE TITLE
New Calculator 

### ISSUE THREAD

**Issue by Saket2701** [SarthakKeshari/calc_for_everything#394]
### Enter calculator name - 
Laplace Transform Calculator

### Describe calculator functionality - 
Computes the Laplace transform of a given function.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Saket2701** [comment]
@SarthakKeshari Kindly assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @Saket2701,
Glad to see your eagerness for contributing 🤩.  This issue has already been addressed.
Hope to see you come up with more innovative issues.

Happy contributing!! 🎉
