### ISSUE TITLE
Delay Calculator (Calculating Propagation Delay)

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#396]
### Enter calculator name - 
Propagation Delay Calculator

### Describe calculator functionality - 
The Propagation Delay Calculator takes the distance between the Sender and the Receiver of the Signal and the speed of Propagation of the Signal, as the name mentions, calculate the Propagation Delay for the Transmission.
It can also be that the Propagation Delay is given and we need to calculate any of the missing values.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Computer Networks
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by sikehish** [comment]
Id like to work on this. Can you assign it to me

**Comment by SarthakKeshari** [comment]
Hey @sikehish,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\propagationDelayCalc

Issue completion deadline - 23rd Oct 7:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by sikehish** [comment]
Hi @SarthakKeshari . I have implemented it. Here's the [PR](https://github.com/SarthakKeshari/calc_for_everything/pull/436)
