### ISSUE TITLE
Decimal to Binary and vice versa Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#4]
### Enter calculator name - 
Decimal to Binary and vice versa

### Describe calculator functionality - 
Calculator will take user input as Decimal/Binary and display output as Binary/Decimal.

### Under which category you wish to place it - 
[x] Computer Science
[] Mathematics
[] Scientific
[] Health
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by abhijithhegde** [comment]
Hey,
can you assign this to me?

**Comment by SarthakKeshari** [comment]
Hey @abhijithhegde,
Assigned

**Comment by SarthakKeshari** [comment]
Hey @abhijithhegde,
You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\DecToBinAndBinToDec

**Comment by abhijithhegde** [comment]
Okay

**Comment by SarthakKeshari** [comment]
Kindly take pull as the codebase is updated.

**Comment by SarthakKeshari** [comment]
Issue completion deadline - 3rd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by ArnabBCA** [comment]
> Issue completion deadline - 3rd Oct 8:00:00 am IST
> 
> _NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant_

Hey can I work on This Issue?

**Comment by SarthakKeshari** [comment]
Hey @ArnabBCA,
I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 
For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉
