### ISSUE TITLE
Inverse of Matrix

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#40]
### Enter calculator name - 
Inverse of Matrix

### Describe calculator functionality - 
Take size of matrix as input from user then take matrix of the specified size as input and display the inverse of the matrix.
### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Sam-bhav-20** [comment]
@SarthakKeshari kindly assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @Sam-bhav-20,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\matrix_inverse

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @Sam-bhav-20, Glad to see your eagerness 😃. Will definitely review shortly.
