### ISSUE TITLE
Delay Calculator (Calculating Transmission Delay)

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#401]
### Enter calculator name - 
Transmission Delay Calculator

### Describe calculator functionality - 
The Transmission Delay Calculator takes the length of the message packet and the transmission rate from the Sender and the Receiver of the Signal, as the name mentions, calculates the Transmission Delay for the Transmission.
It can also be that the Transmission Delay is given and we need to calculate any of the missing values.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Computer Networks
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ravishrivas** [comment]
kindly assign it to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @ravishrivas,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\transmissionDelayCalc

Issue completion deadline - 23rd Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
