### ISSUE TITLE
Delay Calculator (Calculating Setup Delay)

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#402]
### Enter calculator name - 
Setup Delay Calculator

### Describe calculator functionality - 
Given the distance between the Sender and the Receiver of the Signal, the speed of Propagation of the Signal, the length of the message packet, and the transmission rate of the message packet from the Sender to the Receiver of the Signal calculate the Setup Delay.
You can get help from the Propagation Delay and the Transmission Delay Calculators.
It can also be that the Setup Delay is given and we need to calculate any of the missing values.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Computer Networks
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @syash7202,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\setupDelayCalc

Issue completion deadline - 25th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
