### ISSUE TITLE
Kinetic Energy Calculator

### ISSUE THREAD

**Issue by aditya962** [SarthakKeshari/calc_for_everything#403]
### Enter calculator name - 
Kinetic Energy Calculator

### Describe calculator functionality - 
This calculator takes input of mass(kg) and velocity(m/s) and return an output of kinetic energy of that object.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [x] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by aditya962** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @aditya962,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\kineticEnergyCalc

Issue completion deadline - 22nd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
