### ISSUE TITLE
Potential Energy Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#406]
### Enter calculator name - 
Potential Energy Calculator

### Describe calculator functionality - 
The Potential Energy Calculator takes the mass(m) of an object (in kg) , displacement(h) of the object (in metre) from the ground, and gravitational acceleration (g) if not the standard 9.8 ms^(-2).

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by thanmayeem** [comment]
can you please assign it to me

**Comment by SarthakKeshari** [comment]
Hey @thanmayeem,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\potentialEnergyCalc

Issue completion deadline - 23rd Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by IshaanShettigar** [comment]
Kindly assign me this issue as the deadline has passed.

**Comment by SarthakKeshari** [comment]
@thanmayeem,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @IshaanShettigar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\potentialEnergyCalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
