### ISSUE TITLE
Carroll's Cave of Knowledge

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#407]
### Enter calculator name - 
Carroll's Cave of Knowledge

### Describe calculator functionality - 
This Calculator takes one of the inputs and converts it into the different multiples and sub-multiples of that unit in powers of 10.
The range from highest power of measuring unit to the lowest power goes like, yotta -> zetta -> exa -> peta -> tera -> giga -> mega -> kilo -> hecto -> deca -> SI unit -> deci -> centi -> milli -> micro -> nano -> pico -> femto -> atto-> zepto -> yokto

### Under which category you wish to place it - 
- [x] Computer Science
- [x] Mathematics
- [x] Physics
- [x] Chemistry
- [x] Biology
- [ ] Art
- [x] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ravishrivas** [comment]
kindly assign it to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @ravishrivas,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\carrollsCaveOfKnowledge

Issue completion deadline - 23rd Oct 5:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
