### ISSUE TITLE
Delay Calculator (Calculating the order of reaching of packets)

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#412]
### Enter calculator name - 
Delay Calculator (Calculating the order of reaching of packets)

### Describe calculator functionality - 
Given 'n' equal size datagrams belonging to the same message that are conditioned to leave for the destination only one after another, but traveling through different switches i ranging as 1,2,...,n-1,n ; choosing paths from Sender to Receiver that can be either mono or multi switched. The path length of each datagram is also provided by the user using the Calculator. The delay provided at each switch is i*t, where t is equal to 3 milli-seconds (standard). As the propagation speed of the signal in optical fibers is 2/3 of the speed of light. The Calculator calculates the order in which the datagrams finally reach the Receiver.
Example: Sender sends Hello but it might reach the Receiver as Hleol.
Hint: Use the Propagation Delay Calculator and the Transmission Delay Calculator to calculate the setup delay of each datagram.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Computer Networks
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by nipun221** [comment]
@SarthakKeshari kindly assign me this issue.

**Comment by SarthakKeshari** [comment]
Hey @nipun221,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\packetsOrderCalc

Issue completion deadline - 25th Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue will be closed under PR - #512
