### ISSUE TITLE
Work Calculator

### ISSUE THREAD

**Issue by aditish11** [SarthakKeshari/calc_for_everything#415]
### Enter calculator name - 
Work Calculator

### Describe calculator functionality - 
This calculator takes input of Force and Displacement and returns the output as Work in Joule.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by aditish11** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
May you configure this calculator to handle not only Joules but other units of work too. For example - the horsepower-hour, the newton-metre, the foot-pound, the kilowatt-hour, the foot-poundal, and the litre-atmosphere

**Comment by aditish11** [comment]
Yes, thank you for the insights. I will add the other units too.

**Comment by SarthakKeshari** [comment]
Hey @aditish11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\workCalc

Issue completion deadline - 23rd Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
