### ISSUE TITLE
Hooke's Law Calculator

### ISSUE THREAD

**Issue by aditish11** [SarthakKeshari/calc_for_everything#416]
### Enter calculator name - 
Hooke's Law Calculator

### Describe calculator functionality - 
This  calculator takes input of spring displacement, spring force constant and returns force in Newton.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by aditish11** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
May you configure this calculator to handle the below units of Force too? - 
![image](https://github.com/SarthakKeshari/calc_for_everything/assets/55992140/a667125b-b8bd-4f72-8ca4-197e4d67e333)

**Comment by aditish11** [comment]
Yes, thank you for the insights. I will add the other units too.

**Comment by SarthakKeshari** [comment]
Hey @aditish11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\hookesLawCalc

Issue completion deadline - 23rd Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Thanush19** [comment]
can i work on this ...??

**Comment by SarthakKeshari** [comment]
Hey @Thanush19,
Glad to see your eagerness for contributing 🤩. I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 

#### For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉
