### ISSUE TITLE
Adjoint of Matrix

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#42]
### Enter calculator name - 
Adjoint of Matrix

### Describe calculator functionality - 
Take size of matrix as input from user then take matrix of the specified size as input and display the adjoint of the matrix.
### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by uttkarsh1m** [comment]
Hey @SarthakKeshari kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @uttkarsh1m,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\matrix_adjoint

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by kittoteja** [comment]
can you please assign this to me

**Comment by SarthakKeshari** [comment]
I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 
For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉
