### ISSUE TITLE
Z-Score Calculator

### ISSUE THREAD

**Issue by real-varshney** [SarthakKeshari/calc_for_everything#423]
### Enter calculator name - 
Z-Score Calculator

### Describe calculator functionality - 
This Calculator is used to compute the z-score of a normal distribution using mean, standard deviation and raw score.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by real-varshney** [comment]
@SarthakKeshari can you assign this to me.

**Comment by SarthakKeshari** [comment]
Hey @real-varshney,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\zScoreCalc

Issue completion deadline - 23rd Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
