### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by tejxv** [SarthakKeshari/calc_for_everything#433]
### Enter calculator name -  
Convert any link into a QR code image.
### Describe calculator functionality - 
This would take in a URL as input and output an QR Code embeded image.
### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

and I’d like to be assigned to this issue!

**Comment by sikehish** [comment]
Im interested in this. Could you assign this to me?

**Comment by SarthakKeshari** [comment]
Hey @tejxv,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\qRCodeGenerator
#### Kindly also add functionality to download the generated QR Code.

Issue completion deadline - 25rd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @sikehish and @syash7202,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
