### ISSUE TITLE
Base64 Encoder/Decoder

### ISSUE THREAD

**Issue by tejxv** [SarthakKeshari/calc_for_everything#434]
### Enter calculator name - 
Base64 Convertor

### Describe calculator functionality - 
Decode text from Base64 format or Encode text in Base64

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

and I’d like to be assigned to this issue!

**Comment by sikehish** [comment]
I'm interested in working on this.
