### ISSUE TITLE
Rename the title of the website and create a favicon

### ISSUE THREAD

**Issue by sikehish** [SarthakKeshari/calc_for_everything#437]
![Screenshot 2023-10-21 234551](https://github.com/SarthakKeshari/calc_for_everything/assets/90673701/7546eafa-4776-4a6d-a122-9e4185828705)
The creative heads can probably come up with a name and a favicon and give a better identity to the website and the project!

**Comment by SarthakKeshari** [comment]
Hey @sikehish,
Assigned.

Issue completion deadline - 23rd Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by sikehish** [comment]
Working on it!

**Comment by sikehish** [comment]
[PR for this issue](https://github.com/SarthakKeshari/calc_for_everything/pull/438)
