### ISSUE TITLE
Calculator for the gravitational force between 2 bodies

### ISSUE THREAD

**Issue by IshaanShettigar** [SarthakKeshari/calc_for_everything#443]
### Enter calculator name - 
Gravitational Force Calculator

### Describe calculator functionality - 
Should calculate the gravitational force between two bodies. Given the mass of the two bodies and the distance between them.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by IshaanShettigar** [comment]
Please assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @IshaanShettigar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\gravitationalForceCalc

Issue completion deadline - 25rd Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
