### ISSUE TITLE
Variance - Standard Deviation Converter

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#446]
### Enter calculator name - 
Variance - Standard Deviation Converter

### Describe calculator functionality - 
The Variance - Standard Deviation Converter is a calculator that takes one of the two values and finds the other value accordingly.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by VincentPaulV** [comment]
Hey @Vedansh-Keshari !!
I'd like to work on this issue!
If available please assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @VincentPaulV,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\varianceStandardDeviationConverter

Issue completion deadline - 25th Oct 9:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
This issue is closed under PR - #497
