### ISSUE TITLE
Mean Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#447]
### Enter calculator name - 
Mean Calculator

### Describe calculator functionality - 
The Mean Calculator takes the values(data) in the form of a table, the range of classes, (could be even class marks), their respective frequencies, (could be even cumulative frequencies), and calculates the mean of the complete data ( or only the classes the user wants the mean of ) .

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by VincentPaulV** [comment]
Hey @Vedansh-Keshari ,
I'd like to take up this issue!

**Comment by SarthakKeshari** [comment]
This issue is closed under PR - #502
