### ISSUE TITLE
Median Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#448]
Enter calculator name -
Median Calculator

Describe calculator functionality -
The Median Calculator takes the values(data) in the form of a table, the range of classes, (could be even class marks), their respective frequencies, (could be even cumulative frequencies), and calculates the median of the complete data.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Rishika631** [comment]
Can you assign me this issue please?

**Comment by SarthakKeshari** [comment]
Hey @Rishika631,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\statisticsMedianCalc

Issue completion deadline - 25th Oct 9:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Rishika631** [comment]
I have raised a PR. Do check it. Thank you!
