### ISSUE TITLE
Mean Deviation about the Median Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#449]
Enter calculator name -
Mean Deviation about the Median Calculator

Describe calculator functionality -
The Mean Deviation about the Median Calculator takes the values(data) in the form of a table, the range of classes, (could be even class marks), their respective frequencies, (could be even cumulative frequencies), and calculates the mean deviation about median of the complete data in the standard format.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by DeexithParand2k2** [comment]
Hi @Vedansh-Keshari can you assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @DeexithParand2k2,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\meanDeviationAboutMedianCalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by DeexithParand2k2** [comment]
Thanks @SarthakKeshari, I'll complete it and let you know within the deadline.

**Comment by DeexithParand2k2** [comment]
Hi @SarthakKeshari I've completed the task and have raised a PR with appropriate README for the algorithm and the components I've used. Kindly review and merge my PR as soon as possible. Thank you for the opportunity.
