### ISSUE TITLE
Mode Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#451]
### Enter calculator name - 
Mode Calculator

### Describe calculator functionality - 
The Mode Calculator takes the values(data) in the form of a table, the range of classes, (could be even class marks), their respective frequencies, (could be even cumulative frequencies), and finds the modal class and hence calculates the mode of the complete data.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ashishnallana** [comment]
hey @Vedansh-Keshari @SarthakKeshari i would like to work on it.

**Comment by SarthakKeshari** [comment]
Hey @ashishnallana,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\modeCalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by ashishnallana** [comment]
hey @Vedansh-Keshari || @SarthakKeshari can you kindly explain a little bit about the input format, like how the end-user is supposed to add his data, (multiple inputs for each of the columns or something different).

**Comment by SarthakKeshari** [comment]
> hey @Vedansh-Keshari || @SarthakKeshari can you kindly explain a little bit about the input format, like how the end-user is supposed to add his data, (multiple inputs for each of the columns or something different).

@Vedansh-Keshari, Kindly provide your insights

**Comment by Vedansh-Keshari** [comment]
> hey @Vedansh-Keshari || @SarthakKeshari can you kindly explain a little bit about the input format, like how the end-user is supposed to add his data, (multiple inputs for each of the columns or something different).

@ashishnallana , as mentioned in the question, the user input will be the grouped data ( class ranges ) and their respective frequencies.
Interval         |      Frequency   |   Cumulative Frequency
0    -  10                       5                          5
10  -  20                       3                          8
20  -  30                       8                         16
...and so on and so forth.

here is youtube link for clear understanding of the input/output parameters and how this calcultor is expected to work
https://youtu.be/WHZxiAR9bfY?feature=shared

**Comment by ashishnallana** [comment]
@Vedansh-Keshari I got it, thanks for explaining.

**Comment by Vedansh-Keshari** [comment]
@ashishnallana You're welcome.
