### ISSUE TITLE
University GPA Calculator

### ISSUE THREAD

**Issue by IshaanShettigar** [SarthakKeshari/calc_for_everything#458]
### Enter calculator name - 
GPA Calculator

### Describe calculator functionality - 
There are various GPA schemes across the world. The challenges in designing a globally accepted GPA calculator are:
1. Some universities have an A, B, C, D, E, F system. Whereas some others have an A+, A, A- and so on. Some even have the highest grade as an S. 
2. Not all courses are weighted equally, most universities have a credit system. (2 credit courses, 4 credit courses, 5 credit courses etc.)
3. Some GPA's are scored out of 4 where as others are out of 10 etc.

Therefore we need to have a `grade to point` mapping like 

![image](https://github.com/SarthakKeshari/calc_for_everything/assets/77607172/400ee39d-11aa-4255-9655-a0748d3d7f96) 

![image](https://github.com/SarthakKeshari/calc_for_everything/assets/77607172/a3089e7c-e180-4034-b704-2d970a9b24d3)

This mapping will then be used to calculate the GPA.
In general the GPA can be calculated as the total sum of every subjects points*credits divided by the total credits.
We can provide some clean UI for the user to enter the mapping.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let the project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by IshaanShettigar** [comment]
Please assign me this issue

**Comment by SarthakKeshari** [comment]
@IshaanShettigar,
I am labeling this issue as medium, I hope the UI will be as good as the explanation provided for the issue and the pictures that have been attached.

**Comment by SarthakKeshari** [comment]
Hey @IshaanShettigar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\universityGPACalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
