### ISSUE TITLE
Torque Calculator

### ISSUE THREAD

**Issue by aditya962** [SarthakKeshari/calc_for_everything#459]
### Enter calculator name - 
Torque Calculator

### Describe calculator functionality - 
Torque Calculator takes input of Radius(r), Force(N) and angle(theta) and gives output of total torque generated.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by aditya962** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @aditya962,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\torqueCalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
