### ISSUE TITLE
New Calculator : F.O. Ordinary Differential Eq. Calculator

### ISSUE THREAD

**Issue by Kris0011** [SarthakKeshari/calc_for_everything#46]
### Enter calculator name - 
Numerical Methods calculator

### Describe calculator functionality - 
- The calculator allows you to approximate the solution of a first-order ordinary differential equation using different numerical methods. It provides a visual representation of how the numerical methods approximate the solution by evaluating the function at discrete intervals.
- Enter Valid inputs and Select one of the numerical methods - Euler's method, Euler's modified method, or Runge-Kutta's method. This determines the algorithm used to approximate the solution of the differential equation.

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @Kris0011, 
Calculator name sounds a bit generic, do you have any suggestion for the calculator's name?

Here's my suggestion, if it sounds good to you - 
F.O. Ordinary Differential Eq. Calculator

**Comment by SarthakKeshari** [comment]
@Kris0011, Kindly comment if you are willing to take up this issue.

**Comment by Kris0011** [comment]
Yes , name i will change . You can assign me this

**Comment by SarthakKeshari** [comment]
Hey @Kris0011,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\first_order_differential_eq_solver

Issue completion deadline - 4th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Kris0011** [comment]
Yes , But where is package.json file ? its missing
