### ISSUE TITLE
Correcting Grammatical and Spelling Mistakes in the Documentation

### ISSUE THREAD

**Issue by Pasqua101** [SarthakKeshari/calc_for_everything#461]
### What's the issue
While reading through some files, like the [CONTRIBUTING.md](https://github.com/SarthakKeshari/calc_for_everything/blob/master/CONTRIBUTING.md) file, I noticed there were a couple grammatical and spelling mistakes. I would like to fix these to increase readability of the documentation.

### Example of  the Error and Fix
This [line from the CONTRIBUTING.md](https://github.com/SarthakKeshari/calc_for_everything/blob/master/CONTRIBUTING.md#note---not-folowing-the-contribution-guidlines-may-lead-to-permanent-ban-from-repository) says "NOTE - NOT folowing the contribution guidlines may lead to permanent ban from repository."

It should actually say "NOTE - NOT following the contributing guidelines may lead to a permanent ban from the repository"

**Comment by Pasqua101** [comment]
Could you please kindly assign this issue to me with the label of Hacktoberfest?

**Comment by SarthakKeshari** [comment]
@Pasqua101,
Thanks for bringing this up. But resolving such issues is not the aim of this repository as of Hacktoberfest 2023.
You might contribute this after the month of October.

Closing this issue.
