### ISSUE TITLE
Mathematical Averages Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#463]
### Enter calculator name - 
Mathematical Averages Calculator

### Describe calculator functionality - 
The Mathematical Averages Calculator takes a set of values and finds the Arithmetic Mean, Geometric Mean and Harmonic Mean of the same.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by its-kumar-yash** [comment]
@Vedansh-Keshari I want to work on this task, kindly assign this to me

**Comment by SarthakKeshari** [comment]
Hey @its-kumar-yash,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\averagesCalculator

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
