### ISSUE TITLE
MMM Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#464]
### Enter calculator name - 
MMM Calculator

### Describe calculator functionality - 
The MMM Calculator takes two of the three values among Mean, Median, Mode and calculates the other remaining value according to the standard relation established among the three.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Rida-Nuha** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Rida-Nuha,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\mMMCalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
