### ISSUE TITLE
Upgrading hex to octal (vice versa) and dec to octal (vice versa) convertor

### ISSUE THREAD

**Issue by PrachiDev11** [SarthakKeshari/calc_for_everything#465]
### Enter calculator name - 
Upgrading hex to octal (vice versa) and dec to octal (vice versa) convertor

### Describe calculator functionality - 
here we will be Upgrading hex to octal (vice versa) and dec to octal (vice versa) value and make a convertor of it

### Under which category you wish to place it - 
- [x ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by PrachiDev11** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the following folder paths -
### calc_for_everything\calculators\src\computer_science\hexToOctAndOctToHex
### calc_for_everything\calculators\src\computer_science\decToOctAndOctToDec

#### Be careful, do not break the old code already exists.

Issue completion deadline - 25th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
