### ISSUE TITLE
Age calculator

### ISSUE THREAD

**Issue by Vimal-Dubey** [SarthakKeshari/calc_for_everything#47]
### Enter calculator name - 
Age Calculator

### Describe calculator functionality - 
This calculator calculates a person's age based on their birthdate and the current date. It can also calculate the difference in age between two individuals.

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[x] Let project owner decide
[] Suggest a new category - Quantitative Maths

**Comment by SarthakKeshari** [comment]
@Vimal-Dubey, 
I am assigning the calculator under <b>Health</b> category.

Kindly also comment if you wish to work on this calculator.

**Comment by Vimal-Dubey** [comment]
Yes off course I wanna work.
Please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @Vimal-Dubey,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\age_calculator

Issue completion deadline - 4th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by ashishnallana** [comment]
If possible, assign it to me I would like to work on it.

**Comment by SarthakKeshari** [comment]
Hey @ashishnallana,
I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 
For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉
