### ISSUE TITLE
Coefficient of Mean Deviation Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#474]
### Enter calculator name - 
Coefficient of Mean Deviation Calculator

### Describe calculator functionality - 
The Coefficient of Mean Deviation Calculator takes the values(data) in the form of a table, the range of classes, (could be even class marks), their respective frequencies, (could be even cumulative frequencies), and calculates the coefficient of mean deviation of the complete data ( or only the classes the user wants the mean of ) .

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign this to me

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\coefOfMeanDeviationCalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
