### ISSUE TITLE
Drug Half Life / Clearance Calculator

### ISSUE THREAD

**Issue by PrachiDev11** [SarthakKeshari/calc_for_everything#476]
### Enter calculator name - 
Drug Half Life / Clearance Calculator

### Describe calculator functionality - 
here , we calculate the time taken by any drug to get resolve in body in according to half life of any given drug.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [x ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by PrachiDev11** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\biology\drugHalfLifeClearanceCalc

Issue completion deadline - 26th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
