### ISSUE TITLE
Binary String Weight Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#480]
### Enter calculator name - 
Binary String Weight Calculator

### Describe calculator functionality - 
The Binary String Weight Calculator takes a binary String as input and calculates the Hamming weight of the String.
https://math.stackexchange.com/questions/2306756/number-of-binary-and-constant-weight-strings-of-length-m-which-do-not-contain-k
the above provided link can be used for reference.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Kindly provide a more specific link for better reference.

**Comment by Vedansh-Keshari** [comment]
Sorry for the inconvenience faced, I have edited the question. Please go through it again.

**Comment by Ayush-Vish** [comment]
@SarthakKeshari  @Vedansh-Keshari  I would like to work on this issue. Please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @Ayush-Vish,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\binaryStringWeightCalc

Issue completion deadline - 30th Oct 9:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by Ayush-Vish** [comment]
@SarthakKeshari  No problem.
