### ISSUE TITLE
Hamming Distance Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#481]
### Enter calculator name - 
Hamming Distance Calculator

### Describe calculator functionality - 
The Hamming Distance Calculator takes two binary Strings as input and finds the Hamming distance between them by using the weight of each Strings separately.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
This issue has already been addressed.
