### ISSUE TITLE
Co-Prime Finder Extended

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#483]
### Enter calculator name - 
Co-Prime Finder Extended

### Describe calculator functionality - 
The Co-Prime Finder Extended Calculator takes two numbers as input which are the starting and ending points of the range and prints all the co-prime pairs between them inclusive of both. The Calculator should be able to handle if someone gives any unrelated arbitrary values , some being first number greater than the second or any kind of negative integers.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
There will be n number of such pairs. So not required to build a calculator for it.
