### ISSUE TITLE
Number Type Finder III

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#488]
### Enter calculator name - 
Number Type Finder

### Describe calculator functionality - 
Given a number entered by the user, find if the number is -
- Abundant Number
- Disarium Number
- Emirp Number
- Fascinating Number
- Magic Number

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by mannbajpai** [comment]
Hey, @SarthakKeshari please assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @mannbajpai,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\number_type_finder

#### Kindly follow the code format and be careful, do not break the old code already exists. 

Issue completion deadline - 26th Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
