### ISSUE TITLE
Find Number Type 1

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#49]
### Enter calculator name - 
Number Type Finder

### Describe calculator functionality - 
Given a number entered by the user, find if the number is -
- Armstrong Number
- Kaprekar Number
- Automorphic Number
- Perfect Number
- Amicable Number

### Under which category you wish to place it - 
[x] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by ashishnallana** [comment]
I would like to work on it, please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @ashishnallana,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\number_type_finder

Issue completion deadline - 4th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
