### ISSUE TITLE
POSET Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#490]
### Enter calculator name - 
POSET Calculator

### Describe calculator functionality - 
Given a set R of pairs of values, the POSET Calculator takes R as input and checks if it follows the RAT properties of Set Theory ( namely Reflexive, Anti-symmetric and Transitive ) and then outputs if the SET is a POSET or not.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by sikehish** [comment]
Im interested!

**Comment by SarthakKeshari** [comment]
Hey @sikehish,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\pOSETCalc

Issue completion deadline - 30th Oct 9:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by SarthakKeshari** [comment]
Hey @syash7202,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉 

I apologize for the delay in my response, and I appreciate your understanding.

**Comment by sikehish** [comment]
> Hey @sikehish, Assigned.
> 
> You may contribute your code under the folder path -
> ### calc_for_everything\calculators\src\mathematical\pOSETCalc
> 
> Issue completion deadline - 30th Oct 9:00:00 am IST
> 
> _NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant_

Working on it!

**Comment by sikehish** [comment]
> I apologize for the delay in my response, and I appreciate your understanding.

No problem!

**Comment by sikehish** [comment]
@SarthakKeshari It's done [PR](https://github.com/SarthakKeshari/calc_for_everything/pull/534)
