### ISSUE TITLE
Hexadecimal to Binary and vice versa Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#5]
### Enter calculator name - 
Hexadecimal to Binary and vice versa

### Describe calculator functionality - 
Calculator will take user input as Hexadecimal/Binary and display output as Binary/Hexadecimal.

### Under which category you wish to place it - 
[x] Computer Science
[] Mathematics
[] Scientific
[] Health
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by TANYA03GUPTA** [comment]
can you assign it to me? @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @TANYA03GUPTA,
Assigned

**Comment by SarthakKeshari** [comment]
@TANYA03GUPTA , 
You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\HexToBinAndBinToHex

**Comment by SarthakKeshari** [comment]
Kindly take pull as the codebase is updated.

**Comment by TANYA03GUPTA** [comment]
okay will do so. thanks for assigning
