### ISSUE TITLE
Add Binary Subtractor

### ISSUE THREAD

**Issue by ArnabBCA** [SarthakKeshari/calc_for_everything#50]
### Enter calculator name - 
Binary Subtractor

### Describe calculator functionality - 
This binary Subtraction function first ensures that both input binary strings have the same length by padding them with leading zeros if necessary. Then, it performs binary subtraction bit by bit, taking into account borrow when needed. Finally, it removes any leading zeros from the result.

### Under which category you wish to place it - 
[X] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[x] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by ArnabBCA** [comment]
Can i work on this issue?

**Comment by SarthakKeshari** [comment]
Hey @ArnabBCA,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\BinarySubstractor

Issue completion deadline - 4th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by ArnabBCA** [comment]
I think the Substractor spelling is wrong

**Comment by SarthakKeshari** [comment]
@ArnabBCA, My bad. Thanks for pointing that out. Kindly make the required change in filename.

Thankyou
