### ISSUE TITLE
cyclic redudancy check calculator 

### ISSUE THREAD

**Issue by dvtushar** [SarthakKeshari/calc_for_everything#501]
### Enter calculator name - 
Cyclic redudancy check calculator 

### Describe calculator functionality - 
allows you to compute CRC values for data

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by dvtushar** [comment]
kindly assign me this issue

**Comment by dvtushar** [comment]
@Vedansh-Keshari In cyclic redundancy check (CRC), n-bits represent the length of the CRC code, which is a checksum used for error detection in data transmission. The m-bits correspond to the target element or message. The CRC algorithm generates a remainder of n-bits when dividing the target message by a predetermined polynomial, and this remainder is appended to the message for error detection purposes.

**Comment by SarthakKeshari** [comment]
Hey @dvtushar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\cRCCalc

Issue completion deadline - 31th Oct 08:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
