### ISSUE TITLE
Molality Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#510]
### Enter calculator name - 
Molality Calculator

### Describe calculator functionality - 
The Molality Calculator as the name suggests takes the number of moles and the mass of solvent in kgs(SI) or multiples/sub-multiples of it as input and gives the Molality of the given solution as output.
The inputs and outputs are inter-connected, if the user tries to change one of them, the other two values maintain the correct dependency and change along with it.
In case you face a problem in calculating the number of Moles, you can simply refer to the Moles Calculator in the repository.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Please assign this to me

**Comment by SarthakKeshari** [comment]
@Upadhyay-Harshit,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous issues are merged.

**Comment by sikehish** [comment]
I'm interested in solving this

**Comment by SarthakKeshari** [comment]
Hey @sikehish,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\molalityCalc

Issue completion deadline - 31st Oct 08:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by sikehish** [comment]
I've implemented it https://github.com/SarthakKeshari/calc_for_everything/pull/548
