### ISSUE TITLE
 Tip Calculator

### ISSUE THREAD

**Issue by Rida-Nuha** [SarthakKeshari/calc_for_everything#513]
### Enter calculator name - 
Tip Calculator

### Describe calculator functionality - 
 The Tip Calculator is a simple application that helps users determine the appropriate tip amount to leave at a restaurant or for any service based on the total bill and the desired tip percentage. 

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [x] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Rida-Nuha** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Rida-Nuha,
Glad to see your eagerness for contributing 🤩.  This issue has already been addressed.
Hope to see you come up with more innovative issues.

Happy contributing!! 🎉
