### ISSUE TITLE
Fuel Cost Calculator

### ISSUE THREAD

**Issue by Rida-Nuha** [SarthakKeshari/calc_for_everything#514]
### Enter calculator name - 
Fuel Cost Calculator

### Describe calculator functionality - 

A Fuel Cost Calculator is a tool that helps users estimate the cost of a trip or commute based on factors such as distance, fuel efficiency, fuel price, and the number of passengers.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [x] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Rida-Nuha** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @Rida-Nuha,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\fuelCostCalc

Issue completion deadline - 30th Oct 9:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.

**Comment by SarthakKeshari** [comment]
This issue is closed under PR - #616
