### ISSUE TITLE
Molar Mass Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#519]
### Enter calculator name - 
Molar Mass Calculator

### Describe calculator functionality - 
The Molar Mass Calculator takes the amount of the substance in grams ( could be multiples or sub-multiples of the unit ) and moles of that substance and calculates the molar mass of that substance with the standard relation.
The inputs and outputs are inter-connected, if the user tries to change one of them, the other two values maintain the correct dependency and change along with it.
In case you face a problem in calculating the number of Moles, you can simply refer to the Moles Calculator in the repository.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by nipun221** [comment]
@SarthakKeshari kindly assign me this issue

**Comment by Zinc-ion** [comment]
@SarthakKeshari  please assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @Zinc-ion,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\molarMassCalc

Issue completion deadline - 31st Oct 05:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
