### ISSUE TITLE
FD maturity Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#52]
### Enter calculator name - 
FD maturity Calculator

### Describe calculator functionality - 
Take input as amount deposited, rate of interest, date of deposit (non-compulsory field), duration of deposit, compounding frequency (annually by default) and display maturity interest, amount and date of maturity (if date of deposit is provided) on the screen.

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[x] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by hiren2599** [comment]
@SarthakKeshari I would like to work on it, please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @hiren2599,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\fd_maturity_calculator

Issue completion deadline - 4th Oct 2:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
