### ISSUE TITLE
TAT Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#524]
### Enter calculator name - 
TAT Calculator

### Describe calculator functionality - 
Given a Gantt Chart, the array of Arrival Time (ATi) of the Processes and the array of Completion Time (CTi) of the Processes is provided as input, and the TAT Calculator is expected to calculate the Turn Around Time (TATi) of each Process (Pi) along with calculating the Total Turn Around Time and the average Turn Around Time.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by WaterCubeGod** [comment]
Kindly assign this issue to me @SarthakKeshari.

**Comment by SarthakKeshari** [comment]
Hey @WaterCubeGod,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\tATCalc

Issue completion deadline - 31st Oct 08:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
