### ISSUE TITLE
Projectile Range Calculator

### ISSUE THREAD

**Issue by aditish11** [SarthakKeshari/calc_for_everything#526]
### Enter calculator name - 
Projectile Range Calculator

### Describe calculator functionality - 
This calculator takes velocity, angle of launch and initial height as input and gives the range of projectile as output.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by aditish11** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @aditish11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\projectileRangeCalc

Issue completion deadline - 30th Oct 10:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
I apologize for the delay in my response, and I appreciate your understanding.
