### ISSUE TITLE
Momentum Calculator

### ISSUE THREAD

**Issue by Pasqua101** [SarthakKeshari/calc_for_everything#531]
### Enter calculator name - 
I would like to make a momentum calculator.

### Describe calculator functionality - 
The calculator handles the formula p=mv. With p being momentum, m being mass and v being velocity. Mass will hold a value in kilograms (kg) and velocity will hold a value in meters per second (m/s). This returns a value of kg m/s for momentum. The calculator will also hold an explanation of the calculator similar to other ones, as well as an update to the README to mention this calculator.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Pasqua101** [comment]
Could you please assign this issue to me with the label of Hacktoberfest?

**Comment by DeepakGupta1007** [comment]
Could you please assign this issue to me with the label of Hacktoberfest?

**Comment by SarthakKeshari** [comment]
Hey @Pasqua101,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\momentumCalc

Issue completion deadline - 30th Oct 10:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @DeepakGupta1007,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉

**Comment by Pasqua101** [comment]
@SarthakKeshari Thank you. I have implemented the calculator and created a PR for it.
