### ISSUE TITLE
AND operator

### ISSUE THREAD

**Issue by 7twik** [SarthakKeshari/calc_for_everything#54]
### Enter calculator name - 
AND operation of multiple numbers

### Describe calculator functionality - 
Does AND operation of multiple numbers

### Under which category you wish to place it - 
[] Computer Science

**Comment by 7twik** [comment]
I would like to work on this issue

**Comment by SarthakKeshari** [comment]
Hey @7twik,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\and_operator

Issue completion deadline - 4th Oct 3:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
