### ISSUE TITLE
Not Calculator

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#542]
### Enter calculator name - 
Not Calculator 

### Describe calculator functionality - 
Find the not value of a number ?

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upkar0904** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @Upkar0904,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\notCalc

Issue completion deadline - 31st Oct 08:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
