### ISSUE TITLE
Lower Bound - Upper Bound Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#544]
### Enter calculator name - 
Lower Bound - Upper Bound Calculator

### Describe calculator functionality - 
Given two Sets X and Y and a target Set Z ; the Lower Bound - Upper Bound Calculator is supposed to calculate the lower bounds and the upper bounds of the Set Z.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by amwaiting1** [comment]
@SarthakKeshari Please assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @amwaiting1,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\lowerBoundUpperBoundCalc

Issue completion deadline - 31st Oct 05:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
