### ISSUE TITLE
OR operator

### ISSUE THREAD

**Issue by 7twik** [SarthakKeshari/calc_for_everything#55]
### Enter calculator name - 
OR operation of multiple values

### Describe calculator functionality - 
does OR operation on multiple binary values

### Under which category you wish to place it - 
[] Computer Science

**Comment by SarthakKeshari** [comment]
Hey @7twik,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\or_operator

Issue completion deadline - 4th Oct 3:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
