### ISSUE TITLE
Temperature conversion computer

### ISSUE THREAD

**Issue by M111ku** [SarthakKeshari/calc_for_everything#550]
### Enter calculator name - 
Your answer
Temperature conversion computer

### Describe calculator functionality - 
Your answer
The user input the temperature value, select the input unit, click the conversion button, calculate the target temperature using the built-in formula, and update the conversion result in real time.Formula: Implement the Fahrenheit to Celsius conversion formula C = (F-32) / 1.8, and the Celsius to Fahrenheit conversion formula F = C * 1.8 + 32 within the program.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by M111ku** [comment]
Kindly assign this issue to me @SarthakKeshari  ：）

**Comment by SarthakKeshari** [comment]
Hey @M111ku,
Glad to see your eagerness for contributing 🤩.  This issue has already been addressed under Metric Unit Converter Calculator.
Hope to see you come up with more innovative issues.

Happy contributing!! 🎉
