### ISSUE TITLE
Planetary Gravitational Calculator

### ISSUE THREAD

**Issue by wuyu-wy** [SarthakKeshari/calc_for_everything#551]
### Enter calculator name - 
Planetary Gravitational Calculator

### Describe calculator functionality - 
The Planetary Gravitational Calculator is used to calculate gravitational interactions between celestial bodies such as planets, moons, the sun, etc.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [X] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by wuyu-wy** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @wuyu-wy,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\planetaryGravitationalCalc

Issue completion deadline - 31st Oct 06:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
