### ISSUE TITLE
Gravity acceleration calculator

### ISSUE THREAD

**Issue by M111ku** [SarthakKeshari/calc_for_everything#552]
### Enter calculator name - 
Your answer
Gravity acceleration calculator

### Describe calculator functionality - 
Your answer
User input location latitude and longitude, click calculate, the program calls the gravity acceleration formula calculation, and display the results.Calculation formula: According to the longitude and latitude information, call the international gravity formula to calculate the acceleration of gravity. The formula is:
g = 9.780327(1 + 0.0053024sin^2φ - 0.0000058sin^2(2φ))

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by M111ku** [comment]
Kindly assign this issue to me @SarthakKeshari  ：）

**Comment by SarthakKeshari** [comment]
@M111ku,
Kindly let me know if can place this calculator under Physics.

**Comment by M111ku** [comment]
Yes,you can put it in physics.

**Comment by SarthakKeshari** [comment]
Hey @M111ku,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\gravityAccelerationCalc

Issue completion deadline - 31st Oct 05:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
