### ISSUE TITLE
Loan Payment Calculator

### ISSUE THREAD

**Issue by 1520229462** [SarthakKeshari/calc_for_everything#554]
### Enter calculator name - 
Loan Payment Calculator

### Describe calculator functionality - 
Create a calculator to calculate the monthly payment amount and total interest of a loan. The input parameters include the loan amount, interest rate, and loan term. The loan amount refers to the total amount of the loan, the interest rate refers to the annual interest rate of the loan, and the loan term refers to the repayment period of the loan. The output results include the monthly payment amount and total interest. The monthly payment amount can be calculated using the formula for equal monthly installments, and the total interest can be calculated using the following formula: Total Interest = Monthly Payment Amount * Loan Term - Loan Amount.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [x] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by 1520229462** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @1520229462,
Glad to see your eagerness for contributing 🤩.  This issue has already been addressed under #61.
Hope to see you come up with more innovative issues.

Happy contributing!! 🎉
