### ISSUE TITLE
Currency Exchange Calculator

### ISSUE THREAD

**Issue by 1520229462** [SarthakKeshari/calc_for_everything#562]
### Enter calculator name - 
Currency Exchange Calculator

### Describe calculator functionality - 
 Create a calculator that allows users to convert one currency to another based on the current exchange rate. The calculator should provide a convenient way for users to input the amount of the source currency and select the source and target currencies for the conversion. The calculator should then display the converted amount in the target currency.By creating this currency exchange calculator, users can easily convert currencies based on the current exchange rate, providing them with a convenient tool for managing their international transactions and financial planning.

Input Parameters:

Source Currency: The currency to be converted from.
Target Currency: The currency to be converted to.
Amount: The amount of the source currency to be converted.
Output Result:

Converted Amount: The equivalent amount in the target currency based on the current exchange rate.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [x] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by 1520229462** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @1520229462,
Glad to see your eagerness for contributing 🤩.  This issue has already been addressed under #171.
Hope to see you come up with more innovative issues.

Happy contributing!! 🎉
