### ISSUE TITLE
Dice Roller

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#568]
### Enter calculator name - 
Dice Roller

### Describe calculator functionality - 
Roll 1 to 6 dice at a time.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [x] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign it to me

**Comment by SarthakKeshari** [comment]
Hey ,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\sports_games\diceRoller

Issue completion deadline - 31st Oct 11:45:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
