### ISSUE TITLE
Bingo Number Generator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#570]
### Enter calculator name - 
Bingo Number Generator

### Describe calculator functionality - 
Randomly generate bingo numbers to call a bingo game and keep track of all numbers called.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [x] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by shoumik310** [comment]
Hi @SarthakKeshari, I'm interested in working on this. Please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @shoumik310,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\sports_games\bingoNumberGenerator

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@shoumik310,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SakshiJSanghavi** [comment]
@SarthakKeshari Kindly assign me this issue.
