### ISSUE TITLE
Coin Flipper

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#571]
### Enter calculator name - 
Coin Flipper

### Describe calculator functionality - 
Coin Flipper simulates a coin toss for heads or tails.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [x] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ShashWorks** [comment]
Kindly assign this to me 
cc : @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @ShashWorks,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\sports_games\coinFlipper

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
