### ISSUE TITLE
Random Card Generator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#572]
### Enter calculator name - 
Random Card Generator

### Describe calculator functionality - 
Draw 1 to 52 cards randomly from a shuffled deck of playing cards.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [x] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Upadhyay-Harshit** [comment]
Kindly assign this to me

**Comment by SarthakKeshari** [comment]
@Upadhyay-Harshit,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous issues are merged.

**Comment by ShivamPatel-24** [comment]
@SarthakKeshari Please assign this task to me

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari Kindly assign this issue to me.
> 
> Apologies, I missed the part that says wait till the issue is assigned to you. I am a master's student who is assigned a project to have 4 PRs accepted. In order to complete it in a timely manner, I rushed the implementation and PR part a bit.

@ShivamPatel-24,
It is heartening to observe your responsible behavior.
I will assign the issue to you and will review the PR as well.

**Comment by SarthakKeshari** [comment]
Hey @ShivamPatel-24,
Issue has been assigned.
