### ISSUE TITLE
Hooke's Law Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#574]
### Enter calculator name - 
Hooke's Law Calculator

### Describe calculator functionality - 
F = -kx

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [x] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by DapaoK** [comment]
Kindly assgin this issue to me @SarthakKeshari thanks !
