### ISSUE TITLE
Stopwatch

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#576]
### Enter calculator name - 
Stopwatch

### Describe calculator functionality - 
Do provide the functionality of Lap Time, Pause and Resume Stopwatch.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by amwaiting1** [comment]
@SarthakKeshari Please assign this issue to me
