### ISSUE TITLE
Savings Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#58]
### Enter calculator name - 
Savings Calculator

### Describe calculator functionality - 
Get input as <b>Salary</b>, and allow user to enter the as many expenses as he wants. Allow user to enter expense name and amount and then display his Savings. 

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[x] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Saksham-245** [comment]
Hi @SarthakKeshari can you assign this issue to me!

**Comment by Satvik-Garg** [comment]
hi @SarthakKeshari kindly assign me this issue under hacktoberfest2023

**Comment by SarthakKeshari** [comment]
Hey @Saksham-245,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\savings_calc

Issue completion deadline - 4th Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
