### ISSUE TITLE
Character Counter

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#580]
### Enter calculator name - 
Character Counter

### Describe calculator functionality - 
Count characters, words, spaces, tabs and line breaks in a sample of text. Count unique characters to calculate character frequency.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by 1520229462** [comment]
Kindly assign the issue to me

**Comment by 1520229462** [comment]
Kindly assign the issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@1520229462,
Kindly work on the comments provided on your previous Pull request.

**Comment by 1520229462** [comment]
Kindly assign the issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @1520229462,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\characterCounter

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by wuhue** [comment]
Kindly assign this to me

**Comment by SarthakKeshari** [comment]
> What is word? Can you give an example of text to show how many words are in it @SarthakKeshari

He  is good at badminton. 
Ans) 5 words

He
is
good
at
badminton.

**Comment by 1520229462** [comment]
In addition to Spaces, numbers and newlines can also be used as signs to separate words?
