### ISSUE TITLE
Nth Root Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#581]
### Enter calculator name - 
Nth Root Calculator

### Describe calculator functionality - 
Calculate Nth order root of a number

eg - 2 is 3rd order root of 8.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by ShashWorks** [comment]
Kindly assign it to me
cc: @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @ShashWorks,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\nthRootCalc

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
