### ISSUE TITLE
 Solve for Exponents Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#583]
### Enter calculator name - 
Solve for Exponents Calculator

### Describe calculator functionality - 
Enter values x and y into this calculator to solve for the exponent value n in the equation x^n=y

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by wuhue** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @wuhue,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\exponentsSolver

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
