### ISSUE TITLE
Pixels Per Inch PPI Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#588]
### Enter calculator name - 
Pixels Per Inch PPI Calculator

### Describe calculator functionality - 
Calculate screen resolution and pixel density using width and height of display screen in pixels

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Zinc-ion** [comment]
@SarthakKeshari please assign this issue to me

**Comment by Zinc-ion** [comment]
Kindly assgin this issue to me @SarthakKeshari thanks !

**Comment by SarthakKeshari** [comment]
Hey @Zinc-ion,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\pPICalc

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
