### ISSUE TITLE
Diamond Problem Solver

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#591]
### Enter calculator name - 
Diamond Problem Solver

### Describe calculator functionality - 
Enter any two interger values and the calculator will solve for the other two. 
The equations used in the steps to solve for the answer will also be shown.
![image](https://github.com/SarthakKeshari/calc_for_everything/assets/55992140/4c00825c-d3a9-411d-8eda-13850a41043c)

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Alfred-hhy** [comment]
Kindly assgin this issue to me @SarthakKeshari  thanks !

**Comment by Alfred-hhy** [comment]
Kindly assgin this issue to me @Saksham-245  @hiren2599  @tejxv  thanks !

**Comment by SarthakKeshari** [comment]
Hey @Alfred-hhy,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\diamondProblemSolver

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Alfred-hhy** [comment]
Thank you very much for assigning this issue to me. I'm not sure if this interface is acceptable to you.
![image](https://github.com/SarthakKeshari/calc_for_everything/assets/117528325/e648116f-d60b-4c9d-9f5f-a462bc794dcb)

**Comment by Alfred-hhy** [comment]
@SarthakKeshari   Please communicate with me if you have any questions.

**Comment by Alfred-hhy** [comment]
@SarthakKeshari  Please feel free to let me know if there are any modifications needed.

**Comment by SarthakKeshari** [comment]
@Alfred-hhy, Kindly check the PR comment section

**Comment by Alfred-hhy** [comment]
Are you asking if your interface needs to be exactly like the screenshot you described? If so, I apologize; I tried to do it yesterday but didn't succeed, so it looks the way it does now. If possible, please reassign task #589 to me and cancel the current task #591.
thanks !





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SarthakKeshari/calc_for_everything"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月31日(星期二) 凌晨4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SarthakKeshari/calc_for_everything] Diamond Problem Solver (Issue #591)





 
@Alfred-hhy, Kindly check the PR comment section

**Comment by SarthakKeshari** [comment]
@Alfred-hhy,
UI ain't my concern, but the logic and approach is.
The code does not comply by this functionality - `Enter any two interger values and the calculator will solve for the other two.`

As per the issue there are four variables A, B, Product, Sum. So if any two is provided other two needs to be calculated.

**Comment by Alfred-hhy** [comment]
@SarthakKeshari 
Oh, I see! That's how it is. Thank you for patiently explaining. I misunderstood your requirements earlier. I'll make the necessary adjustments again.
