### ISSUE TITLE
Golden Ratio Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#594]
### Enter calculator name - 
Golden Ratio Calculator

### Describe calculator functionality - 
The golden ratio, also known as the golden mean, is the value phi where phi = (A+B)/A = A/B.
Find values that satisfy the golden ratio where (A+B):A = A:B. 
Enter any ratio term to calculate the missing golden ratio values.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by 1520229462** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @1520229462,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\goldenRatioCalc

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by 1520229462** [comment]
The input is a ratio term, and the output is a value of the missing golden ratio. Please tell me, am I understanding this correctly？ @SarthakKeshari

**Comment by 1520229462** [comment]
Or maybe I got it wrong somewhere else

**Comment by SarthakKeshari** [comment]
@1520229462,
So, the requirement is there should be 3 input boxes - A+B, A and B
So, if any two box has the value then  3rd value will be calculated automatically.

So output should look like - 

Value of A+B: Value of A = Value of A: Value of B

**Comment by 1520229462** [comment]
Thank you. I understand
