### ISSUE TITLE
Compound Interest Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#6]
### Enter calculator name - 
Compound Interest

### Describe calculator functionality - 
Take principal, rate of interest, time and compounding frequency as input from user and provide interest and amount as output

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Scientific
[] Health
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Saksham-245** [comment]
Hi @SarthakKeshari can you assign this issue to me. Also can you provide some more specific details about this issue.

**Comment by SarthakKeshari** [comment]
Hi @Saksham-245, 
Assigned

**Comment by SarthakKeshari** [comment]
I have created a simple interest calculator in the react app, so similarly you may create a compound interest calculator, with an extra field that takes into consideration whether compounding is happening, monthly, quaterly, semi-annually or annually.

**Comment by SarthakKeshari** [comment]
@Saksham-245, You may contribute your code under the folder path - 
### calc_for_everything\calculators\src\mathematical\compound_interest

**Comment by SarthakKeshari** [comment]
Kindly take pull as the codebase is updated.

**Comment by Saksham-245** [comment]
Sure!
