### ISSUE TITLE
Vieta Theorem Calculator

### ISSUE THREAD

**Issue by DapaoK** [SarthakKeshari/calc_for_everything#601]
### Enter calculator name - 
Vieta Theorem Calculator

### Describe calculator functionality - 
Unary quadratic equations: ax^2+bx+c=0(a≠0)  x1+x2=-b/a x1x2=c/a

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by 1520229462** [comment]
Kindly assign this issue to me

**Comment by Upadhyay-Harshit** [comment]
kindly assign this to me

**Comment by SarthakKeshari** [comment]
Hey @Upadhyay-Harshit,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\vietaTheoremCalc

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
