### ISSUE TITLE
Degree - Radian Converter

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#606]
### Enter calculator name - 
Degree - Radian Converter

### Describe calculator functionality - 
The Degree - Radian Converter takes an input in Degrees and converts it into Radians and vice-versa.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by VincentPaulV** [comment]
Hey @SarthakKeshari !!
Can I take up this issue?

Thanks!!

**Comment by SarthakKeshari** [comment]
This issue has already been addressed.

Happy contributing!! 🎉
