### ISSUE TITLE
Internal Angles of a Polygon

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#607]
### Enter calculator name - 
Internal Angles of a Polygon

### Describe calculator functionality - 
This Calculator takes the number of sides/vertices of a convex polygon as input and calculates the sum of all internal angles of it.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by VincentPaulV** [comment]
Hey @SarthakKeshari , @Vedansh-Keshari !!
Can I take up this issue?

Thanks!!

**Comment by SarthakKeshari** [comment]
Hey @VincentPaulV,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\internalAnglesOfAPolygon

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
