### ISSUE TITLE
External Angles of a Polygon

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#608]
### Enter calculator name - 
External Angles of a Polygon

### Describe calculator functionality - 
This Calculator takes the number of sides/vertices of a convex polygon as input and calculates each of the external angles of it.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by hubsMIT1** [comment]
Hi @Vedansh-Keshari, @SarthakKeshari,
I'm interested in working on this. Could you assign it to me?

**Comment by SarthakKeshari** [comment]
Hey @hubsMIT1,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\externalAnglesOfAPolygonCalc

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by hubsMIT1** [comment]
can you explain the, why the sum of all external angle?
It always will be 360 , am I right?
Or Output should be the angle of each external side?

**Comment by Vedansh-Keshari** [comment]
@hubsMIT1 ,
Good catch, I had created this issue to calculate each external angle of the polygon. 
Thanks for highlighting, I will update the calculator functionality of this issue.

Thanks once again,
Happy Contributing 🎉
