### ISSUE TITLE
Co-interior Pairs

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#609]
### Enter calculator name - 
Co-interior Pairs

### Describe calculator functionality - 
The Co-interior Pairs Calculator takes the value of one angle of the co-interior pair and calculates the value of the other angle.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by hubsMIT1** [comment]
Hey @SarthakKeshari , @Vedansh-Keshari!
Can I work on this issue?

**Comment by SarthakKeshari** [comment]
Hey @hubsMIT1,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\coInteriorPairs

Issue completion deadline - 31st Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
