### ISSUE TITLE
Loan Repayment Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#61]
### Enter calculator name - 
Loan Repayment Calculator

### Describe calculator functionality - 
Get Loan amount taken, rate of interest from the user. 
The user can enter monthly installment amount he wishes to pay to repay the loan, the calculator will then display number of months/years it will take to repay the loan.
<b>OR</b>
The user can enter in how many of months/years he wants to repay the loan, so calculate the monthly installment amount he should pay.
Also display <b>total interest and amount</b> paid by him at the end of the loan closure.

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[x] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Saksham-245** [comment]
Hi @SarthakKeshari can you also assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @Saksham-245,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\loan_repayment_calc

Issue completion deadline - 4th Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
