### ISSUE TITLE
Decimal to Hexadecimal and vice versa

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#63]
### Enter calculator name - 
Decimal to Hexadecimal and vice versa

### Describe calculator functionality - 
Calculator will take user input as Hexadecimal/Decimal and display output as Decimal/Hexadecimal.

### Under which category you wish to place it - 
[X] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by anushka-srivastava22** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @anushka-srivastava22,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\decToHexAndHexToDec

Issue completion deadline - 4th Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
