### ISSUE TITLE
Roofing Calculator

### ISSUE THREAD

**Issue by Shantanu-Tiwari** [SarthakKeshari/calc_for_everything#630]
### Enter calculator name - 
Roofing Calculator

### Describe calculator functionality - 
It estimates the area of roof and the cost for roofing.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [x] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
@Upadhyay-Harshit,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous issues are merged.

**Comment by Shantanu-Tiwari** [comment]
Do add the hacktoberfest label if its acceptable.

**Comment by Vedansh-Keshari** [comment]
Hey ,
@Shantanu-Tiwari .

You may contribute your code under the folder path -
calc_for_everything\calculators\src\finance\roofingCalc

Issue completion deadline - 31st Oct 11:00:00 pm IST

NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant
