### ISSUE TITLE
Hexadecimal to Octal and vice versa

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#64]
### Enter calculator name - 
Hexadecimal to Octal and vice versa

### Describe calculator functionality - 
Calculator will take user input as Hexadecimal/Octal and display output as Octal/Hexadecimal.

### Under which category you wish to place it - 
[X] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by anushka-srivastava22** [comment]
Kindly assign this issue to me

**Comment by Satvik-Garg** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @anushka-srivastava22,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\hexToOctAndOctToHex

Issue completion deadline - 4th Oct 6:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
