### ISSUE TITLE
Feature Addition to Momentum Calculator

### ISSUE THREAD

**Issue by Pasqua101** [SarthakKeshari/calc_for_everything#645]
Hi @SarthakKeshari, if possible I would like to expand on the Momentum Calculator I made in issue #531. To solve for Momentum in that calculator, the mass is measured in kilograms, and the velocity in meters per second. However, mass can also be measured in grams, pounds and ounces. Velocity can be measured in inches per second, centimeters per second, and more.

If approved, I would like to allow the user to find momentum using different measurements for velocity and mass, this will be done by using a combo box menu which will allow the user to select the measurements they want to use.

**Comment by SarthakKeshari** [comment]
@Pasqua101,
Glad that you wish to enhance the Momentum Calculator.

**Comment by SarthakKeshari** [comment]
Hey @Pasqua101,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\momentumCalc

Issue completion deadline - 1st Dec 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new contributor*
