### ISSUE TITLE
Updating Density Calculator

### ISSUE THREAD

**Issue by Pasqua101** [SarthakKeshari/calc_for_everything#647]
Hi @SarthakKeshari, I figured that since I've updated the momentum calculator to accept different units of measurement for velocity and mass. I should do something similar for the density calculator I made in issue #346. 

Essentially, I would like to add additional units of measurement for volume and mass used in the density calculator. In a similar method that was done for my previous issue.

**Comment by SarthakKeshari** [comment]
Hey @Pasqua101,
Your inputs are welcome. The issue has been assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\densityCalc

Issue completion deadline - 04th Dec 01:30:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new contributor*

**Comment by Pasqua101** [comment]
Thank you. Created a PR for the enhancement.
