### ISSUE TITLE
Velocity root mean square value

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#650]
### Enter calculator name - 
Velocity root mean square value

### Describe calculator functionality - 
Given the Molecular Formula of the fluid, which can be used to calculate M (mass in kilograms) to plug into the formula for Vrms and the temperature T in Kelvins, the Calculator is expected to take these inputs into account and also use the Boltzmann constant to calculate the value of Vrms for the particular fluid.
In case you face a problem in calculating the Molecular Weight from the Molecular Formula, you can simply refer to the Molecular Weight Calculator in the repository.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [x] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by Rishika631** [comment]
Please assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @Rishika631,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\velocityRootMeanSquareCalc

Issue completion deadline - 20th Dec 01:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new contributor*

**Comment by Rishika631** [comment]
@SarthakKeshari please assign #589 too.

**Comment by Rishika631** [comment]
@SarthakKeshari the folder has not been created and velocity average and most probable are in physics folder so should I add it in that only ?

**Comment by SarthakKeshari** [comment]
Thanks for bringing this up. Folders have been added as per the above instructions.

**Comment by Rishika631** [comment]
@SarthakKeshari I have raised PR for this issue.
