### ISSUE TITLE
Velocity Average Value

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#653]
### Enter calculator name - 
Velocity Average Value

### Describe calculator functionality - 
Given the Molecular Formula of the fluid, which can be used to calculate M (mass in kilograms) to plug into the formula for Vav and the temperature T in Kelvins, the Calculator is expected to take these inputs into account and also use the Boltzmann constant and pi constant to calculate the value of Vav for the particular fluid.
In case you face a problem in calculating the Molecular Weight from the Molecular Formula, you can simply refer to the Molecular Weight Calculator in the repository.

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [x] Physics
- [x] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SarthakKeshari** [comment]
Hey @Rishika631,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\physics\velocityAverageValueCalc

Issue completion deadline - 17th Dec 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new contributor*

**Comment by Rishika631** [comment]
@SarthakKeshari I have raised the PR for this. Please check

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari I have raised the PR for this. Please check

Sure
