### ISSUE TITLE
Stem Volume Calculator

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#658]
### Enter calculator name - 
Stem Volume Calculator

### Describe calculator functionality - 
The Stem Volume Calculator takes the DBH (diameter at breast height) of the tree as input and uses it to calculate the area A of the cross-section; it also takes the height H of the tree and multiplies these two quantities to find the Volume V, given by `V = A x H`

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Games/Sports
- [x] Let the project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by SakshiJSanghavi** [comment]
@SarthakKeshari Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @SakshiJSanghavi,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\stemVolumeCalc

Issue completion deadline - 17th Dec 09:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new contributor*
