### ISSUE TITLE
Decimal to Octal and vice versa

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#66]
### Enter calculator name - 
Decimal to Octal and vice versa

### Describe calculator functionality - 
Calculator will take user input as Decimal/Octal and display output as Octal/Decimal.

### Under which category you wish to place it - 
[X] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by anushka-srivastava22** [comment]
Kindly assign this issue me

**Comment by SarthakKeshari** [comment]
@anushka-srivastava22,
Abiding by the contribution policy, not more than 2 issues can be assigned at a time.

Kindly comment once the previous issues are merged.

**Comment by shreyashsingh-101** [comment]
Can you assign me this issue?

**Comment by capsy14** [comment]
Hi @SarthakKeshari ! I'm interested in working on this issue. Is it possible to assign it to me?

**Comment by SarthakKeshari** [comment]
Hey @capsy14,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\decToOctAndOctToDec

Issue completion deadline - 4th Oct 7:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Reminder issue is nearing deadline. 

#### NOTE - Issue will get unassigned if the deadline is crossed.

**Comment by Akash0420** [comment]
Since the completion deadline is crossed, Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Akash0420,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\decToOctAndOctToDec

Issue completion deadline - 6th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
