### ISSUE TITLE
XOR Calculator

### ISSUE THREAD

**Issue by chauhansumitdev** [SarthakKeshari/calc_for_everything#67]
### Enter calculator name -  
XOR Calculator

### Describe calculator functionality - 
The calculator should be able to calculate the xor of the two input values.

### Under which category you wish to place it - 
[yes] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide

**Comment by Satvik-Garg** [comment]
kindly asssign me his issue

**Comment by SarthakKeshari** [comment]
Hey @Satvik-Garg,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\xor_operator

Issue completion deadline - 4th Oct 7:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
