### ISSUE TITLE
Expense tracker

### ISSUE THREAD

**Issue by capsy14** [SarthakKeshari/calc_for_everything#68]
### Enter calculator name - 
Expenses tracker

### Describe calculator functionality - 
It will help individuals or businesses manage their finances by tracking and calculating expenses.

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Finance
[] Scientific

**Comment by capsy14** [comment]
@SarthakKeshari Please assign this issue to me :)

**Comment by SarthakKeshari** [comment]
Hey @capsy14, 
There is a savings tracker that is serving a similar purpose #58, kindly look into it and let me know if you have a different plan for this calculator, else we may close this issue.

Thankyou.

**Comment by SarthakKeshari** [comment]
@capsy14,
Sounds good. Ok then let me make 10-pointer issue for keeping a view of enhancing the visuals using Chart.js
And I will provide appreciation points if speech recognition works perfect.

I appreciate a creative view towards the issue and will assign it to you in a few moments.

**Comment by SarthakKeshari** [comment]
Hey @capsy14,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\expense_tracker

Issue completion deadline - 4th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@capsy14, 
Considering the efforts, you have put in, upgrading issue status from **medium** -> **hard** 📈

👏👏
