### ISSUE TITLE
Octal to Binary conversion and vice versa

### ISSUE THREAD

**Issue by 7twik** [SarthakKeshari/calc_for_everything#7]
### Enter calculator name - 
Octal to binary and vice versa

### Describe calculator functionality - 
converts a string/number from octal to binary and vice versa

### Under which category you wish to place it - 
[] Computer Science

**Comment by 7twik** [comment]
Opened this issue, pls assign this issue to me for Hacktoberfest '23

**Comment by SarthakKeshari** [comment]
Hey @7twik,
Assigned

**Comment by SarthakKeshari** [comment]
@7twik,
You may contribute your code under the folder path -

### calc_for_everything\calculators\src\computer_science\OctToBinAndBinToOct

**Comment by SarthakKeshari** [comment]
Kindly take pull as the codebase is updated.
