### ISSUE TITLE
ASCII text to binary and vice versa 

### ISSUE THREAD

**Issue by Saifullah00** [SarthakKeshari/calc_for_everything#70]
### Enter calculator name - 
ASCII text to binary and vice versa 

### Describe calculator functionality - 
The application provides a simple way for users to convert text between ASCII and binary representations. Users can enter text in one format, click the corresponding conversion button, and see the result in the other format. Material-UI components are used to enhance the user interface and provide a polished look and feel.

### Under which category you wish to place it - 
[x] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[x] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by mohak34** [comment]
Hello @Saifullah00 I would like to work on this

**Comment by SarthakKeshari** [comment]
Hey @mohak34 and @Saifullah00,
In order to get the issue assigned kindly leave a comment for example - "Kindly assign it to me" or "Hey, I wish to work on this", as per the contribution guidelines.

Happy Contributing!! 🎉

**Comment by Saifullah00** [comment]
Kindly assign it to me under hactoberfest'23.
Thank you

**Comment by SarthakKeshari** [comment]
Hey @Saifullah00,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\asciiTextToBinAndBinToAsciiText

Issue completion deadline - 4th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Saifullah00** [comment]
Thank you @SarthakKeshari will complete it before deadline
