### ISSUE TITLE
pH calculator

### ISSUE THREAD

**Issue by Saifullah00** [SarthakKeshari/calc_for_everything#71]
### Enter calculator name - 
pH Calculator

### Describe calculator functionality - 
This application allows users to input a pH value, click the "Calculate pH" button, and see whether the pH is acidic, neutral, or alkaline. 

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[x] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[x] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Saifullah00** [comment]
Please assign this to me under hactoberfest.
Thank you
@SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @Saifullah00,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\chemistry\phCalc

Issue completion deadline - 4th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Saifullah00** [comment]
Thank you @SarthakKeshari
