### ISSUE TITLE
Sorting Visualizer

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#74]
### Enter calculator name - 
Sorting Visualizer

### Describe calculator functionality - 
Given a comma separated list of values. Provide a sorted result.
Create a visualizer to visually represent the sorting algorithms. 
### Under which category you wish to place it - 
[x] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by maskboyAvi** [comment]
@SarthakKeshari I would like to make this Sorting Visualizer. Please assign it to me.

**Comment by Sam-bhav-20** [comment]
hey @SarthakKeshari kindly assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @maskboyAvi,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\sorting_visualizer

Issue completion deadline - 5th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @Sam-bhav-20,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
