### ISSUE TITLE
Searching Visualizer

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#75]
### Enter calculator name - 
Searching Visualizer

### Describe calculator functionality - 
Given a comma separated list of values and a value to search. 
Create a visualizer to visually represent the searching algorithms. 
### Under which category you wish to place it - 
[x] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Sam-bhav-20** [comment]
hey @SarthakKeshari kindly assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @maskboyAvi,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\searching_visualizer

Issue completion deadline - 5th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
