### ISSUE TITLE
🥳 Contributors eligible for Contribution Certificate

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#77]
# Congratulations!! 🎉🥳

<div style="display:flex; justify-content: center">
  <img src="https://github.com/7twik.png" width="80px;" style="margin-right:15;"/>   
  <img src="https://github.com/imsoumik03.png" width="80px;" style="margin-right:15"/>
</div>

## Kindly visit here to claim your certificates between *1st November* to *10th November*

**Comment by 7twik** [comment]
well how am i supposed to claim my certificate?
