### ISSUE TITLE
Add Pregnancy Due Date Calculator

### ISSUE THREAD

**Issue by Vimal-Dubey** [SarthakKeshari/calc_for_everything#78]
### Enter calculator name - 
Pregnancy Due Date Calculator

### Describe calculator functionality - 
Determines the estimated due date for a pregnant patient based on the date of their last menstrual period.

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[x] Health
[] Sports
[x] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Vimal-Dubey** [comment]
i want this issue to be assigned to me

**Comment by TOLU-MICH** [comment]
please assign the issue to me, and i think it should grouped under the health category

**Comment by SarthakKeshari** [comment]
Hey @Vimal-Dubey,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\health\pregnancy_due_date_calc

Issue completion deadline - 5th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @TOLU-MICH,
Glad to see your eagerness for contributing 🤩. We are following <b>first come first serve</b>. If deadline is not met, then only it can be assigned to a new participant.
For now, kindly look into any open issues or you may even create one. 🥳

Happy contributing🎉
