### ISSUE TITLE
Add currency convertion functionality

### ISSUE THREAD

**Issue by TOLU-MICH** [SarthakKeshari/calc_for_everything#81]
### Enter calculator name - 
Your answer

### Describe calculator functionality - 
Your answer
it would be used to convert a currency to another one

### Under which category you wish to place it - 
[] Computer Science
[] Mathematics
[] Physics
[] Chemistry
[] Biology
[ . ] Finance
[] Scientific
[] Health
[] Sports
[x] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by Musak2** [comment]
can i work on this?

**Comment by SarthakKeshari** [comment]
Hey @Musak2,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\finance\currency_converter

Issue completion deadline - 5th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @TOLU-MICH,
In order to get the issue assigned kindly leave a comment for example - "Kindly assign it to me" or "Hey, I wish to work on this", as per the contribution guidelines.

Happy Contributing!! 🎉

**Comment by TOLU-MICH** [comment]
kindly assign it to me

**Comment by SarthakKeshari** [comment]
Hey @TOLU-MICH,
I regret to inform, <b>issue can't be assigned</b> as each assigned issue is marked with a <b>deadline</b>. In case the previous participant fails to raise a PR before the deadline, <b>only then the issue can be assigned to a new participant.</b> 
For now, kindly look into any open issues or you may even create one. 🤩

Happy Contributing 🎉

**Comment by Musak2** [comment]
I pushed the code for the currency converter. Is everything okay? Is there anything to be done with the provided code?

**Comment by SarthakKeshari** [comment]
@Musak2,
Kindly raise a PR that will help me review your code

**Comment by Musak2** [comment]
I kindly announce that I have raised a PR for a review. Please write if there is anything else that needs to be done.

**Comment by SarthakKeshari** [comment]
@Musak2, Kindly check the PR comments section for my review comments
