### ISSUE TITLE
Work and Time Calculator

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/calc_for_everything#82]
### Enter calculator name - 
Time And Work Calculator

### Describe calculator functionality - 
We will take number of workers as input (max:4) from the user and then we will take number of hours/days each worker takes to complete the task and then calculate number of days/hours workers will take while working in a group of 2, 3 or 4, depending on no. of workers entered by the user.

### Under which category you wish to place it - 
[] Computer Science
[X] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by anushka-srivastava22** [comment]
Kindly Assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @anushka-srivastava22,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\workAndTimeCalc

Issue completion deadline - 5th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@anushka-srivastava22,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by Amitkm-450** [comment]
Kindly Assign this issue to me

**Comment by SarthakKeshari** [comment]
Hey @Amitkm-450,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\workAndTimeCalc

Issue completion deadline - 11th Oct 2:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Amitkm-450** [comment]
Could you please elaborate the problem statement(i.e. the input  format and output). It will be helpful if you provide an example for user input and expected output for it .

**Comment by SarthakKeshari** [comment]
Sure @Amitkm-450,
Lets take an example -
User input no. of workers as 3.
and provide time taken by each worker to do the work.

Workers are A, B and C

So output should be 
Time taken when A and B work together - 
Time taken when A and C work together - 
Time taken when B and C work together - 
Time taken when A, B and C work together - 


Same goes for cases when number of workers are 2 or 4

**Comment by SarthakKeshari** [comment]
@Amitkm-450,
I am extending the deadline.

Issue completion deadline - 14th Oct 10:00:00 am IST
*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@Amitkm-450,
Any update on the issue?

**Comment by Amitkm-450** [comment]
I have an interview scheduled on 17th so I am busy with that . So , I will
not be able to work on it till 17th of November. Sorry for that.

**Comment by SarthakKeshari** [comment]
@Amitkm-450, Wish you the best for your interview. 👍

**Comment by Moh1tsingh** [comment]
Can you assign this issue to me?

**Comment by PrachiDev11** [comment]
kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Hey @PrachiDev11,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\workAndTimeCalc

Issue completion deadline - 24th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
Hey @syash7202,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\workAndTimeCalc

Issue completion deadline - 29th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@syash7202,
We have to assume 1 work needs to be done. 
Given,
A take x hours to complete it.
B take y hours to complete it.
C take z hours to complete it.

So, in how much time work can be completed if - 
A and B work together - <ANSWER>
A and C work together - <ANSWER>
B and C work together - <ANSWER>
A, B and C work together - <ANSWER>


<ANSWER> - This needs to be calculated by this calculator

**Comment by SarthakKeshari** [comment]
@syash7202,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by ShivamPatel-24** [comment]
@SarthakKeshari Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
Hey @ShivamPatel-24,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\workAndTimeCalc

Issue completion deadline - 12th Dec 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@ShivamPatel-24,
Kindly go through the comment thread above to understand the problem statement.
