### ISSUE TITLE
Finding Co-linear Points

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#85]
### Enter calculator name - 
Finding Co-linear Points

### Describe calculator functionality - 
As we know, 2 points are always co-linear. 
So, this calculator aims to find groups (containing 3 or more points) of points that are co-linear.
User will be asked to how many points they want to check (min:3, max:6) and then (x,y) for all the points will be taken as input.
If points are found co-linear display the group of those points, else display - "No Co-linear Points"

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

**Comment by aniketsinha5552** [comment]
Hey @SarthakKeshari I would like to work on this. Please assign it to me.

**Comment by SarthakKeshari** [comment]
Hey @aniketsinha5552,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\coLinearPointsFinder

Issue completion deadline - 5th Oct 11:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
