### ISSUE TITLE
Finding points lying on same side of line

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/calc_for_everything#86]
### Enter calculator name - 
Finding points lying on same side of line

### Describe calculator functionality - 
So, this calculator aims to find 2 groups of points that lie on opposite side of line.
User will be asked to how many points they want to check (min: 2) and then (x,y) for all the points will be taken as input.
All the points on the same side of the line will be grouped together, while the points that lie on the other side of the line will be grouped together.

### Under which category you wish to place it - 
- [] Computer Science
- [x] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Ayushlion8** [comment]
Hey @SarthakKeshari , I am interested in resolving this issue please assign it to me:)

**Comment by SarthakKeshari** [comment]
Hey @Ayushlion8,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\pointsOnSameSideOfLineFinder

Issue completion deadline - 5th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment]
@Ayushlion8,
Considering the efforts, you have put in, upgrading issue status from easy -> medium 📈

👏👏
