### ISSUE TITLE
ML Model Performance Evaluation Calculator

### ISSUE THREAD

**Issue by Celebi07** [SarthakKeshari/calc_for_everything#89]
### Enter calculator name - 
ML Model Performance Evaluation Calculator

### Describe calculator functionality - 
We propose creating a Model Performance Evaluator tool that takes in the predicted values and actual labels from a machine learning model and calculates various performance metrics such as accuracy, precision, recall, F1-score, and ROC AUC. This tool will be a valuable addition to our machine learning workflow, allowing us to easily assess and compare different models and iterations.

### Under which category you wish to place it - 
- [x] Computer Science
- [] Mathematics
- [] Physics
- [] Chemistry
- [] Biology
- [] Finance
- [] Scientific
- [] Health
- [] Sports
- [x] Let project owner decide
- [] Suggest a new category - _(Answer here)_

**Comment by Celebi07** [comment]
@SarthakKeshari I would like to build this calculator. Please assign it to me :)

**Comment by SarthakKeshari** [comment]
Hey @Celebi07,
I appreciate the ideology behind this calculator. Adding it to admin-choice list.

**Comment by SarthakKeshari** [comment]
Hey @Celebi07,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\mLModelPerformanceEvaluationCalculator

Issue completion deadline - 5th Oct 1:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
