### ISSUE TITLE
Binary Adder

### ISSUE THREAD

**Issue by 7twik** [SarthakKeshari/calc_for_everything#9]
### Enter calculator name - 
Binary addition

### Describe calculator functionality - 
adds 2 binary no.

### Under which category you wish to place it - 
[] Computer Science

**Comment by 7twik** [comment]
Opened this issue, pls assign me this issue

**Comment by SarthakKeshari** [comment]
Hey @7twik ,
Assigned

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\BinaryAdder
