### ISSUE TITLE
Polynomial Equation Integral calculator

### ISSUE THREAD

**Issue by mohammedasimahmed** [SarthakKeshari/calc_for_everything#96]
### Polynomial Equation Integral calculator - 
Provide your polynomial equation which must be provided in the following format a*x^2 + b*x + c to get its integral

### Helps to find integral of polynomial equation easily- 
Provide your polynomial equation which must be provided in the following format a*x^2 + b*x + c to get its integral

### Mathematics

**Comment by SarthakKeshari** [comment]
@mohammedasimahmed,  
Kindly consider going for polynomial equations rather than quadratic.

**Comment by mohammedasimahmed** [comment]
Ok

**Comment by SarthakKeshari** [comment]
Hey @mohammedasimahmed,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\polynomialEqIntegralCalc

Issue completion deadline - 5th Oct 8:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by IshaanShettigar** [comment]
Why has this Issue not been closed? If there is still work to be done then I'd like to work on it.

**Comment by SarthakKeshari** [comment]
Hey @IshaanShettigar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\polynomialEqIntegralCalc

Issue completion deadline - 29th Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
