### ISSUE TITLE
Polynomial Equation Differential Calculator

### ISSUE THREAD

**Issue by mohammedasimahmed** [SarthakKeshari/calc_for_everything#98]
### Polynomial Equation Differential calculator -
Provide your polynomial equation which must be provided in the following format a*x^2 + b*x + c to get its differential

### Helps to find differential of polynomial equation easily-
Provide your polynomial equation which must be provided in the following format a*x^2 + b*x + c to get its differential

### Mathematics

**Comment by mohammedasimahmed** [comment]
@SarthakKeshari I would like to build this , please assign me this issue

**Comment by SarthakKeshari** [comment]
@mohammedasimahmed,
Kindly consider going for polynomial equations rather than quadratic.

**Comment by mohammedasimahmed** [comment]
Ok

**Comment by SarthakKeshari** [comment]
@mohammedasimahmed, I will be assigning this issue to you shortly. Keeping polynomial into consideration.

**Comment by Finesse-734** [comment]
@SarthakKeshari  Could you assign this issue to me ..... if it is still open for contribution that is?

**Comment by SarthakKeshari** [comment]
Hey @Finesse-734,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\polynomialEqDifferentialCalc

Issue completion deadline - 25th Oct 10:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by IshaanShettigar** [comment]
Since the date has passed, I'd like to contribute to this now

**Comment by SarthakKeshari** [comment]
@Finesse-734,
Since the issue completion deadline is crossed, 
Issue has been unassigned. 
### Kindly do not create a PR for the issue now.

**Comment by SarthakKeshari** [comment]
Hey @IshaanShettigar,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\polynomialEqDifferentialCalc

Issue completion deadline - 31st Oct 8:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*
