### ISSUE TITLE
LCM calculator 

### ISSUE THREAD

**Issue by mohammedasimahmed** [SarthakKeshari/calc_for_everything#99]
### LCM calculator  - 
finds the lcm of the given numbers

**Comment by mohammedasimahmed** [comment]
@SarthakKeshari please assign me this issue

**Comment by Sam-bhav-20** [comment]
@SarthakKeshari please assign me this

**Comment by SarthakKeshari** [comment]
Hey @Sam-bhav-20,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\mathematical\lcmCalc

Issue completion deadline - 5th Oct 11:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by Sam-bhav-20** [comment]
@SarthakKeshari is there any max limit of numbers to find lcm?

**Comment by SarthakKeshari** [comment]
@Sam-bhav-20, Kindly go for max LCM of 6 numbers and each number should not exceed 1000.
